from pathlib import Path

from devflows.actions import ref as action_ref
from devflows.catalog import Workflow, load_catalog
from devflows.publish import (
    _ensure_job_permissions,
    build_published_workflow,
    caller_required_permissions,
    render_published_workflow,
    validate_publish_config,
)


def _workflow(workflow_id: str):
    return {item.id: item for item in load_catalog()}[workflow_id]


def _make_workflow(metadata: dict, workflow: dict) -> Workflow:
    return Workflow(
        id=str(metadata.get("id", "demo")),
        path=Path("workflows/demo"),
        workflow_path=Path("workflows/demo/workflow.yaml"),
        metadata_path=Path("workflows/demo/devflow.yaml"),
        metadata=metadata,
        workflow=workflow,
    )


def test_pandoc_source_workflow_only_declares_domain_inputs() -> None:
    pandoc = _workflow("pandoc")
    source_inputs = pandoc.workflow_call["inputs"]

    assert list(source_inputs) == [
        "pandoc-arguments",
        "pandoc-image",
        "pandoc-working-directory",
        "pandoc-timeout-minutes",
    ]
    assert "checkout-enabled" not in source_inputs
    assert "artifact-upload-enabled" not in source_inputs
    assert "patch-emit-enabled" not in source_inputs


def test_pandoc_published_workflow_injects_shared_io_interface() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    inputs = workflow["on"]["workflow_call"]["inputs"]
    secrets = workflow["on"]["workflow_call"]["secrets"]

    assert inputs["checkout-enabled"]["default"] is True
    assert inputs["artifact-download-enabled"]["default"] is False
    assert inputs["artifact-upload-enabled"]["default"] is False
    assert inputs["patch-emit-enabled"]["default"] is False
    assert (
        inputs["patch-artifact-name"]["default"]
        == "devflows-pandoc-patch-${{ github.run_id }}-${{ github.run_attempt }}"
    )
    assert "checkout-token" in secrets
    assert "artifact-download-token" in secrets
    # The patch-emit channel forces no secret (no commit token on the caller).
    assert "commit-token" not in secrets


def test_pandoc_published_workflow_injects_shared_io_steps_and_patch_emit() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    steps = workflow["jobs"]["pandoc"]["steps"]

    assert [step["name"] for step in steps] == [
        "Checkout repository",
        "Download artifacts",
        "Materialize DevFlows runtime scripts",
        "Run Pandoc",
        "Upload artifact",
        "Create workspace patch",
        "Upload workspace patch",
        "Collect job outputs",
    ]
    # No nested commit job: patch-emit forces no contents: write anywhere.
    assert "commit" not in workflow["jobs"]
    assert all("write" not in str(job.get("permissions", {})) for job in workflow["jobs"].values())


def test_pandoc_materialize_step_inlines_referenced_scripts() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    materialize = next(
        step for step in workflow["jobs"]["pandoc"]["steps"] if step.get("id") == "devflows-runtime"
    )
    run = materialize["run"]

    # Only its own domain script is inlined; patch-emit inlines no script.
    assert 'cat > "$RUNNER_TEMP/devflows/pandoc/run-pandoc.py"' in run
    assert "create-payload.py" not in run
    assert "<<'DEVFLOWS_SCRIPT_EOF'" in run
    assert 'echo "script-root=$RUNNER_TEMP/devflows" >> "$GITHUB_OUTPUT"' in run
    # No runtime checkout of the devflows repo remains.
    assert "github.workflow_ref" not in render_published_workflow(pandoc)


def test_pandoc_patch_emit_capture_uses_no_caller_input() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    capture = next(
        step
        for step in workflow["jobs"]["pandoc"]["steps"]
        if step.get("name") == "Create workspace patch"
    )
    # Injection-safe: the capture is pure git with no ${{ inputs.* }} interpolation.
    assert "${{" not in capture["run"]
    assert "git diff --cached --binary" in capture["run"]
    assert capture["if"] == "inputs.patch-emit-enabled"


def test_writeback_publishes_with_inlined_apply_patch() -> None:
    writeback = _workflow("writeback")
    workflow = build_published_workflow(writeback)
    steps = workflow["jobs"]["writeback"]["steps"]

    assert steps[0]["name"] == "Materialize DevFlows runtime scripts"
    assert 'cat > "$RUNNER_TEMP/devflows/writeback/apply-patch.py"' in steps[0]["run"]
    # writeback is the sole holder of contents: write.
    assert workflow["jobs"]["writeback"]["permissions"]["contents"] == "write"
    rendered = render_published_workflow(writeback)
    assert rendered.startswith("# GENERATED by devflows sync")
    assert "github.workflow_ref" not in rendered


def test_devcontainer_build_source_replaces_monolithic_config() -> None:
    devcontainer_build = _workflow("devcontainer-build")
    inputs = devcontainer_build.workflow_call["inputs"]

    assert "config" not in inputs
    assert inputs["image-name"]["required"] is True
    assert "build-matrix" in inputs
    assert "prepare-command" in inputs
    assert "devcontainer-run-cmd" not in inputs
    assert "docker-registry-auth" not in inputs
    assert "cache-save-always" not in inputs


def test_devcontainer_build_published_workflow_injects_checkout_and_runtime_job() -> None:
    workflow = build_published_workflow(_workflow("devcontainer-build"))
    build_steps = workflow["jobs"]["build-devcontainer"]["steps"]
    merge_steps = workflow["jobs"]["merge-devcontainer"]["steps"]

    assert [step["name"] for step in build_steps[:5]] == [
        "Checkout repository",
        "Download artifacts",
        "Materialize DevFlows runtime scripts",
        "Prepare workspace",
        "Resolve build settings",
    ]
    assert [step["name"] for step in merge_steps[:2]] == [
        "Materialize DevFlows runtime scripts",
        "Docker login",
    ]


def test_devcontainer_build_published_workflow_filters_conflicting_action_inputs() -> None:
    rendered = render_published_workflow(_workflow("devcontainer-build"))

    assert "fromJSON(inputs.config)" not in rendered
    assert "runCmd:" not in rendered
    assert "subFolder:" not in rendered
    assert "inheritEnv:" not in rendered
    assert "skipContainerUserIdUpdate:" not in rendered
    assert "registry-auth:" not in rendered
    assert "save-always:" not in rendered
    assert "docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0" in rendered
    assert "docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c" in rendered
    assert "devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca" in rendered


def test_devcontainer_build_exposes_build_only_digest_proof() -> None:
    # item 13: a build-only run can prove an image was produced by capturing the
    # local digest and uploading it under build-digest-artifact-name.
    build = _workflow("devcontainer-build")
    inputs = build.workflow_call["inputs"]
    assert "build-digest-artifact-name" in inputs

    workflow = build_published_workflow(build)
    step_names = [step.get("name") for step in workflow["jobs"]["build-devcontainer"]["steps"]]
    assert "Capture build-only image digest" in step_names
    assert "Upload build-only image digest" in step_names


# --------------------------------------------------------------- item 9: permissions


def test_ensure_job_permissions_seeds_workflow_level_when_job_has_none() -> None:
    # A job with no permissions block inherits workflow-level today; introducing
    # a job-level block for a channel scope must carry the workflow grants along,
    # or job-level replacement silently drops packages: write.
    job: dict = {"steps": []}
    _ensure_job_permissions(job, {"packages": "write"}, contents="read", actions="read")

    assert job["permissions"] == {
        "packages": "write",
        "contents": "read",
        "actions": "read",
    }


def test_ensure_job_permissions_keeps_inheritance_when_workflow_level_covers_channels() -> None:
    job: dict = {"steps": []}
    _ensure_job_permissions(
        job, {"contents": "read", "actions": "read"}, contents="read", actions="read"
    )

    assert "permissions" not in job  # nothing to add; keep inheriting workflow-level


def test_ensure_job_permissions_preserves_explicit_empty_deny_all() -> None:
    job: dict = {"steps": [], "permissions": {}}
    _ensure_job_permissions(job, {"contents": "read"}, contents=None, actions=None)

    assert job["permissions"] == {}  # never pop an author-declared block


def test_ensure_job_permissions_augments_existing_block_without_removing_keys() -> None:
    job: dict = {"steps": [], "permissions": {"contents": "read"}}
    _ensure_job_permissions(job, {"packages": "write"}, contents="read", actions="read")

    assert job["permissions"] == {"contents": "read", "actions": "read"}


# ------------------------------------------------- item 10: validate_publish_config


def _script_step() -> dict:
    return {
        "steps": [
            {
                "name": "Run",
                "env": {
                    "DEVFLOWS_SCRIPT_ROOT": "${{ steps.devflows-runtime.outputs.script-root }}"
                },
                "run": 'python "${DEVFLOWS_SCRIPT_ROOT}/demo/run.py"',
            }
        ]
    }


def test_validate_rejects_io_job_listed_as_runtime_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True, "runtime-jobs": ["demo"]}},
        {"jobs": {"demo": _script_step()}},
    )

    errors = validate_publish_config(item)

    assert any("must not also appear in io.runtime-jobs" in error for error in errors)


def test_validate_rejects_script_reference_in_unmaterialized_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True}},
        {"jobs": {"demo": {"steps": []}, "rogue": _script_step()}},
    )

    errors = validate_publish_config(item)

    assert any("'rogue'" in error and "DEVFLOWS_SCRIPT_ROOT" in error for error in errors)


def test_validate_accepts_script_reference_in_runtime_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True, "runtime-jobs": ["helper"]}},
        {"jobs": {"demo": {"steps": []}, "helper": _script_step()}},
    )

    assert validate_publish_config(item) == []


# ------------------------------------------------- item 11: inlined script integrity


# ------------------------------------------------- multi-job channel injection


def _multi_job_workflow(
    io_overrides: dict | None = None,
    *,
    workflow_permissions: dict | None = None,
) -> Workflow:
    """A python-build-shaped fixture: a dist io.job plus cibw/conda sibling jobs."""
    io = {
        "job": "dist",
        "checkout": True,
        "artifact-download": True,
        "checkout-jobs": ["cibw", "conda"],
        "artifact-download-jobs": ["conda"],
    }
    if io_overrides:
        io.update(io_overrides)

    def _job(step_name: str) -> dict:
        return {"runs-on": "ubuntu-latest", "steps": [{"name": step_name, "run": "true"}]}

    workflow = {
        "on": {"workflow_call": {}},
        "permissions": (
            workflow_permissions if workflow_permissions is not None else {"contents": "read"}
        ),
        "jobs": {
            "dist": _job("Build sdist"),
            "cibw": _job("Build wheels"),
            "conda": _job("Build conda"),
        },
    }
    return _make_workflow({"id": "python-build", "io": io}, workflow)


def test_multi_job_injects_channel_steps_into_matrix_jobs() -> None:
    jobs = build_published_workflow(_multi_job_workflow())["jobs"]

    assert [step["name"] for step in jobs["dist"]["steps"]] == [
        "Checkout repository",
        "Download artifacts",
        "Build sdist",
    ]
    # cibw is a checkout-only sibling.
    assert [step["name"] for step in jobs["cibw"]["steps"]] == [
        "Checkout repository",
        "Build wheels",
    ]
    # conda receives both channels, in the same relative order as io.job.
    assert [step["name"] for step in jobs["conda"]["steps"]] == [
        "Checkout repository",
        "Download artifacts",
        "Build conda",
    ]


def test_multi_job_injected_steps_use_registry_pins_and_shared_inputs() -> None:
    jobs = build_published_workflow(_multi_job_workflow())["jobs"]
    cibw_checkout = jobs["cibw"]["steps"][0]
    conda_download = jobs["conda"]["steps"][1]

    assert cibw_checkout["uses"] == action_ref("checkout")
    assert conda_download["uses"] == action_ref("download-artifact")
    # Same rendered inputs as the io.job's own channel step (one source of truth).
    assert cibw_checkout["with"] == jobs["dist"]["steps"][0]["with"]
    assert conda_download["with"] == jobs["dist"]["steps"][1]["with"]


def test_multi_job_runtime_materialize_follows_checkout_and_download() -> None:
    workflow = build_published_workflow(
        _multi_job_workflow({"runtime": True, "runtime-jobs": ["cibw", "conda"]})
    )
    jobs = workflow["jobs"]

    # A checkout+runtime job: materialize lands after checkout, before user steps.
    assert [step["name"] for step in jobs["cibw"]["steps"]] == [
        "Checkout repository",
        "Materialize DevFlows runtime scripts",
        "Build wheels",
    ]
    # A checkout+download+runtime job keeps channel order, then materialize.
    assert [step["name"] for step in jobs["conda"]["steps"]] == [
        "Checkout repository",
        "Download artifacts",
        "Materialize DevFlows runtime scripts",
        "Build conda",
    ]


def test_multi_job_permission_seeding_preserves_workflow_grant() -> None:
    # Workflow-level grants only packages: write. Introducing a job-level block for a
    # channel scope must carry that grant along (the fixed seeding semantics).
    jobs = build_published_workflow(
        _multi_job_workflow(workflow_permissions={"packages": "write"})
    )["jobs"]

    assert jobs["cibw"]["permissions"] == {"packages": "write", "contents": "read"}
    assert jobs["conda"]["permissions"] == {
        "packages": "write",
        "contents": "read",
        "actions": "read",
    }


def test_multi_job_checkout_only_inherits_when_workflow_grants_contents() -> None:
    jobs = build_published_workflow(_multi_job_workflow())["jobs"]

    # Workflow-level already grants contents: read, so a checkout-only job keeps
    # inheriting it (no job-level block introduced).
    assert "permissions" not in jobs["cibw"]
    # conda still needs actions: read, which the workflow level lacks -> seeded block.
    assert jobs["conda"]["permissions"] == {"contents": "read", "actions": "read"}


def test_validate_rejects_unknown_checkout_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "dist", "checkout": True, "checkout-jobs": ["ghost"]}},
        {"jobs": {"dist": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any("io.checkout-jobs item 'ghost' must be a runner job" in error for error in errors)


def test_validate_rejects_checkout_job_duplicate_of_io_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "dist", "checkout": True, "checkout-jobs": ["dist"]}},
        {"jobs": {"dist": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any("must not also appear in io.checkout-jobs" in error for error in errors)


def test_validate_rejects_download_jobs_without_channel_enabled() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "dist", "artifact-download-jobs": ["helper"]}},
        {"jobs": {"dist": {"steps": []}, "helper": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any(
        "io.artifact-download-jobs requires io.artifact-download" in error for error in errors
    )


def test_validate_accepts_valid_multi_job_config() -> None:
    item = _make_workflow(
        {
            "id": "demo",
            "io": {
                "job": "dist",
                "checkout": True,
                "artifact-download": True,
                "checkout-jobs": ["cibw"],
                "artifact-download-jobs": ["cibw"],
            },
        },
        {"jobs": {"dist": {"steps": []}, "cibw": {"steps": []}}},
    )

    assert validate_publish_config(item) == []


def test_multi_job_generated_output_snapshot() -> None:
    workflow = build_published_workflow(
        _multi_job_workflow(
            {
                "runtime": True,
                "artifact-upload": True,
                "runtime-jobs": ["cibw", "conda"],
            }
        )
    )
    step_names = {
        job_id: [step["name"] for step in job["steps"]] for job_id, job in workflow["jobs"].items()
    }

    assert step_names == {
        "dist": [
            "Checkout repository",
            "Download artifacts",
            "Materialize DevFlows runtime scripts",
            "Build sdist",
            "Upload artifact",
        ],
        "cibw": [
            "Checkout repository",
            "Materialize DevFlows runtime scripts",
            "Build wheels",
        ],
        "conda": [
            "Checkout repository",
            "Download artifacts",
            "Materialize DevFlows runtime scripts",
            "Build conda",
        ],
    }


def test_render_leaves_uses_line_inside_inlined_script_untouched(make_catalog) -> None:
    from devflows.catalog import load_workflow

    # A script whose body contains a real pinned `uses:` line must survive the
    # dump/annotate pipeline byte-for-byte (no version comment injected), and the
    # integrity check must accept it.
    pin_line = f"# uses: {action_ref('checkout')}\n"
    root = make_catalog(script_body=pin_line + "print('ok')\n")
    import os

    original = Path.cwd()
    try:
        os.chdir(root)
        rendered = render_published_workflow(load_workflow(Path("workflows/demo")))
    finally:
        os.chdir(original)

    assert pin_line.rstrip() in rendered
    assert "# v7.0.0" not in rendered


# ------------------------------------------------- job-output channel


def _job_output_item(io_overrides: dict | None = None, *, jobs: dict | None = None) -> Workflow:
    io = {"job": "demo", "runtime": True, "job-output": True}
    if io_overrides:
        io.update(io_overrides)
    workflow = {
        "on": {"workflow_call": {}},
        "permissions": {"contents": "read"},
        "jobs": jobs
        or {"demo": {"runs-on": "ubuntu-latest", "steps": [{"name": "Do", "run": "true"}]}},
    }
    return _make_workflow({"id": "demo", "io": io}, workflow)


def test_job_output_injects_step_input_and_merged_outputs() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    call = workflow["on"]["workflow_call"]

    # A single statically-declared string input feeds the channel.
    assert call["inputs"]["job-output-map"]["default"] == ""
    assert call["inputs"]["job-output-map"]["type"] == "string"

    step = next(
        s for s in workflow["jobs"]["pandoc"]["steps"] if s.get("id") == "devflows-job-output"
    )
    assert step["name"] == "Collect job outputs"
    assert step["if"] == "inputs.job-output-map != ''"
    # Inputs reach the collector only via env, never interpolated into the run body.
    assert step["env"]["DEVFLOWS_JOB_OUTPUT_MAP"] == "${{ inputs.job-output-map }}"
    assert step["run"] == 'python "${DEVFLOWS_SCRIPT_ROOT}/_channels/collect-job-outputs.py"'
    assert "${{ inputs.job-output-map }}" not in step["run"]

    # The io.job exposes the merged output; workflow_call re-exports it.
    assert (
        workflow["jobs"]["pandoc"]["outputs"]["job-outputs"]
        == "${{ steps.devflows-job-output.outputs.job-outputs }}"
    )
    assert call["outputs"]["job-outputs"]["value"] == "${{ jobs.pandoc.outputs.job-outputs }}"

    # The compact collector is inlined into the io.job's materialize step.
    materialize = next(
        s for s in workflow["jobs"]["pandoc"]["steps"] if s.get("id") == "devflows-runtime"
    )
    assert 'cat > "$RUNNER_TEMP/devflows/_channels/collect-job-outputs.py"' in materialize["run"]


def test_job_output_preserves_author_domain_outputs() -> None:
    # devcontainer-run declares container-id/remote-user on its io.job; the channel
    # must merge job-outputs beside them, never overwrite the author's outputs.
    workflow = build_published_workflow(_workflow("devcontainer-run"))
    run_job = workflow["jobs"]["run"]

    assert run_job["outputs"]["container-id"] == "${{ steps.run.outputs.container-id }}"
    assert run_job["outputs"]["remote-user"] == "${{ steps.run.outputs.remote-user }}"
    assert (
        run_job["outputs"]["job-outputs"] == "${{ steps.devflows-job-output.outputs.job-outputs }}"
    )
    call_outputs = workflow["on"]["workflow_call"]["outputs"]
    assert {"container-id", "remote-user", "job-outputs"} <= set(call_outputs)


def test_job_output_adds_no_caller_permission() -> None:
    base = caller_required_permissions(
        build_published_workflow(_job_output_item({"job-output": False}))
    )
    with_channel = caller_required_permissions(build_published_workflow(_job_output_item()))

    assert with_channel == base  # the channel forces no extra caller permission


def test_validate_rejects_job_output_without_runtime() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "job-output": True}},
        {"jobs": {"demo": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any("io.job-output requires io.runtime" in error for error in errors)


def test_validate_rejects_job_output_on_matrix_io_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True, "job-output": True}},
        {"jobs": {"demo": {"strategy": {"matrix": {"os": ["a", "b"]}}, "steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any("io.job-output cannot target the matrix job 'demo'" in error for error in errors)


def test_validate_rejects_job_output_domain_key_collision() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True, "job-output": True}},
        {"jobs": {"demo": {"steps": [], "outputs": {"job-outputs": "${{ steps.x.outputs.y }}"}}}},
    )

    errors = validate_publish_config(item)

    assert any("already declares an output named 'job-outputs'" in error for error in errors)
