from pathlib import Path

from devflows.actions import ref as action_ref
from devflows.catalog import Workflow, load_catalog
from devflows.publish import (
    _ensure_job_permissions,
    build_published_workflow,
    render_published_workflow,
    validate_publish_config,
)


def _workflow(workflow_id: str):
    return {item.id: item for item in load_catalog()}[workflow_id]


def _make_workflow(metadata: dict, workflow: dict) -> Workflow:
    return Workflow(
        id=str(metadata.get("id", "demo")),
        path=Path("workflows/demo"),
        workflow_path=Path("workflows/demo/workflow.yaml"),
        metadata_path=Path("workflows/demo/devflow.yaml"),
        metadata=metadata,
        workflow=workflow,
    )


def test_pandoc_source_workflow_only_declares_domain_inputs() -> None:
    pandoc = _workflow("pandoc")
    source_inputs = pandoc.workflow_call["inputs"]

    assert list(source_inputs) == [
        "pandoc-arguments",
        "pandoc-image",
        "pandoc-working-directory",
        "pandoc-timeout-minutes",
    ]
    assert "checkout-enabled" not in source_inputs
    assert "artifact-upload-enabled" not in source_inputs
    assert "commit-enabled" not in source_inputs


def test_pandoc_published_workflow_injects_shared_io_interface() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    inputs = workflow["on"]["workflow_call"]["inputs"]
    secrets = workflow["on"]["workflow_call"]["secrets"]

    assert inputs["checkout-enabled"]["default"] is True
    assert inputs["artifact-download-enabled"]["default"] is False
    assert inputs["artifact-upload-enabled"]["default"] is False
    assert inputs["commit-enabled"]["default"] is False
    assert (
        inputs["commit-internal-artifact-name"]["default"]
        == "devflows-pandoc-writeback-${{ github.run_id }}-${{ github.run_attempt }}"
    )
    assert "checkout-token" in secrets
    assert "artifact-download-token" in secrets
    assert "commit-token" in secrets


def test_pandoc_published_workflow_injects_shared_io_steps_and_commit_job() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    steps = workflow["jobs"]["pandoc"]["steps"]

    assert [step["name"] for step in steps] == [
        "Checkout repository",
        "Download artifacts",
        "Materialize DevFlows runtime scripts",
        "Run Pandoc",
        "Upload artifact",
        "Create writeback payload",
        "Upload writeback payload",
    ]
    assert workflow["jobs"]["commit"]["uses"] == "./.github/workflows/writeback.yaml"
    assert workflow["jobs"]["commit"]["needs"] == "pandoc"


def test_pandoc_materialize_step_inlines_referenced_scripts() -> None:
    pandoc = _workflow("pandoc")
    workflow = build_published_workflow(pandoc)
    materialize = next(
        step for step in workflow["jobs"]["pandoc"]["steps"] if step.get("id") == "devflows-runtime"
    )
    run = materialize["run"]

    # Its own script and the writeback create-payload script are inlined.
    assert 'cat > "$RUNNER_TEMP/devflows/pandoc/run-pandoc.py"' in run
    assert 'cat > "$RUNNER_TEMP/devflows/writeback/create-payload.py"' in run
    assert "<<'DEVFLOWS_SCRIPT_EOF'" in run
    assert 'echo "script-root=$RUNNER_TEMP/devflows" >> "$GITHUB_OUTPUT"' in run
    # No runtime checkout of the devflows repo remains.
    assert "github.workflow_ref" not in render_published_workflow(pandoc)


def test_writeback_publishes_with_inlined_apply_payload() -> None:
    writeback = _workflow("writeback")
    workflow = build_published_workflow(writeback)
    steps = workflow["jobs"]["writeback"]["steps"]

    assert steps[0]["name"] == "Materialize DevFlows runtime scripts"
    assert 'cat > "$RUNNER_TEMP/devflows/writeback/apply-payload.py"' in steps[0]["run"]
    rendered = render_published_workflow(writeback)
    assert rendered.startswith("# GENERATED by devflows sync")
    assert "github.workflow_ref" not in rendered


def test_build_devcontainer_source_replaces_monolithic_config() -> None:
    build_devcontainer = _workflow("build-devcontainer")
    inputs = build_devcontainer.workflow_call["inputs"]

    assert "config" not in inputs
    assert inputs["image-name"]["required"] is True
    assert "build-matrix" in inputs
    assert "prepare-command" in inputs
    assert "devcontainer-run-cmd" not in inputs
    assert "docker-registry-auth" not in inputs
    assert "cache-save-always" not in inputs


def test_build_devcontainer_published_workflow_injects_checkout_and_runtime_job() -> None:
    workflow = build_published_workflow(_workflow("build-devcontainer"))
    build_steps = workflow["jobs"]["build-devcontainer"]["steps"]
    merge_steps = workflow["jobs"]["merge-devcontainer"]["steps"]

    assert [step["name"] for step in build_steps[:5]] == [
        "Checkout repository",
        "Download artifacts",
        "Materialize DevFlows runtime scripts",
        "Prepare workspace",
        "Resolve build settings",
    ]
    assert [step["name"] for step in merge_steps[:2]] == [
        "Materialize DevFlows runtime scripts",
        "Docker login",
    ]


def test_build_devcontainer_published_workflow_filters_conflicting_action_inputs() -> None:
    rendered = render_published_workflow(_workflow("build-devcontainer"))

    assert "fromJSON(inputs.config)" not in rendered
    assert "runCmd:" not in rendered
    assert "subFolder:" not in rendered
    assert "inheritEnv:" not in rendered
    assert "skipContainerUserIdUpdate:" not in rendered
    assert "registry-auth:" not in rendered
    assert "save-always:" not in rendered
    assert "docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0" in rendered
    assert "docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c" in rendered
    assert "devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca" in rendered


def test_build_devcontainer_exposes_build_only_digest_proof() -> None:
    # item 13: a build-only run can prove an image was produced by capturing the
    # local digest and uploading it under build-digest-artifact-name.
    build = _workflow("build-devcontainer")
    inputs = build.workflow_call["inputs"]
    assert "build-digest-artifact-name" in inputs

    workflow = build_published_workflow(build)
    step_names = [step.get("name") for step in workflow["jobs"]["build-devcontainer"]["steps"]]
    assert "Capture build-only image digest" in step_names
    assert "Upload build-only image digest" in step_names


# --------------------------------------------------------------- item 9: permissions


def test_ensure_job_permissions_seeds_workflow_level_when_job_has_none() -> None:
    # A job with no permissions block inherits workflow-level today; introducing
    # a job-level block for a channel scope must carry the workflow grants along,
    # or job-level replacement silently drops packages: write.
    job: dict = {"steps": []}
    _ensure_job_permissions(job, {"packages": "write"}, contents="read", actions="read")

    assert job["permissions"] == {
        "packages": "write",
        "contents": "read",
        "actions": "read",
    }


def test_ensure_job_permissions_keeps_inheritance_when_workflow_level_covers_channels() -> None:
    job: dict = {"steps": []}
    _ensure_job_permissions(
        job, {"contents": "read", "actions": "read"}, contents="read", actions="read"
    )

    assert "permissions" not in job  # nothing to add; keep inheriting workflow-level


def test_ensure_job_permissions_preserves_explicit_empty_deny_all() -> None:
    job: dict = {"steps": [], "permissions": {}}
    _ensure_job_permissions(job, {"contents": "read"}, contents=None, actions=None)

    assert job["permissions"] == {}  # never pop an author-declared block


def test_ensure_job_permissions_augments_existing_block_without_removing_keys() -> None:
    job: dict = {"steps": [], "permissions": {"contents": "read"}}
    _ensure_job_permissions(job, {"packages": "write"}, contents="read", actions="read")

    assert job["permissions"] == {"contents": "read", "actions": "read"}


# ------------------------------------------------- item 10: validate_publish_config


def _script_step() -> dict:
    return {
        "steps": [
            {
                "name": "Run",
                "env": {
                    "DEVFLOWS_SCRIPT_ROOT": "${{ steps.devflows-runtime.outputs.script-root }}"
                },
                "run": 'python "${DEVFLOWS_SCRIPT_ROOT}/demo/run.py"',
            }
        ]
    }


def test_validate_rejects_io_job_listed_as_runtime_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True, "runtime-jobs": ["demo"]}},
        {"jobs": {"demo": _script_step()}},
    )

    errors = validate_publish_config(item)

    assert any("must not also appear in io.runtime-jobs" in error for error in errors)


def test_validate_rejects_script_reference_in_unmaterialized_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True}},
        {"jobs": {"demo": {"steps": []}, "rogue": _script_step()}},
    )

    errors = validate_publish_config(item)

    assert any("'rogue'" in error and "DEVFLOWS_SCRIPT_ROOT" in error for error in errors)


def test_validate_accepts_script_reference_in_runtime_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "demo", "runtime": True, "runtime-jobs": ["helper"]}},
        {"jobs": {"demo": {"steps": []}, "helper": _script_step()}},
    )

    assert validate_publish_config(item) == []


# ------------------------------------------------- item 11: inlined script integrity


# ------------------------------------------------- multi-job channel injection


def _multi_job_workflow(
    io_overrides: dict | None = None,
    *,
    workflow_permissions: dict | None = None,
) -> Workflow:
    """A python-build-shaped fixture: a dist io.job plus cibw/conda sibling jobs."""
    io = {
        "job": "dist",
        "checkout": True,
        "artifact-download": True,
        "checkout-jobs": ["cibw", "conda"],
        "artifact-download-jobs": ["conda"],
    }
    if io_overrides:
        io.update(io_overrides)

    def _job(step_name: str) -> dict:
        return {"runs-on": "ubuntu-latest", "steps": [{"name": step_name, "run": "true"}]}

    workflow = {
        "on": {"workflow_call": {}},
        "permissions": (
            workflow_permissions if workflow_permissions is not None else {"contents": "read"}
        ),
        "jobs": {
            "dist": _job("Build sdist"),
            "cibw": _job("Build wheels"),
            "conda": _job("Build conda"),
        },
    }
    return _make_workflow({"id": "python-build", "io": io}, workflow)


def test_multi_job_injects_channel_steps_into_matrix_jobs() -> None:
    jobs = build_published_workflow(_multi_job_workflow())["jobs"]

    assert [step["name"] for step in jobs["dist"]["steps"]] == [
        "Checkout repository",
        "Download artifacts",
        "Build sdist",
    ]
    # cibw is a checkout-only sibling.
    assert [step["name"] for step in jobs["cibw"]["steps"]] == [
        "Checkout repository",
        "Build wheels",
    ]
    # conda receives both channels, in the same relative order as io.job.
    assert [step["name"] for step in jobs["conda"]["steps"]] == [
        "Checkout repository",
        "Download artifacts",
        "Build conda",
    ]


def test_multi_job_injected_steps_use_registry_pins_and_shared_inputs() -> None:
    jobs = build_published_workflow(_multi_job_workflow())["jobs"]
    cibw_checkout = jobs["cibw"]["steps"][0]
    conda_download = jobs["conda"]["steps"][1]

    assert cibw_checkout["uses"] == action_ref("checkout")
    assert conda_download["uses"] == action_ref("download-artifact")
    # Same rendered inputs as the io.job's own channel step (one source of truth).
    assert cibw_checkout["with"] == jobs["dist"]["steps"][0]["with"]
    assert conda_download["with"] == jobs["dist"]["steps"][1]["with"]


def test_multi_job_runtime_materialize_follows_checkout_and_download() -> None:
    workflow = build_published_workflow(
        _multi_job_workflow({"runtime": True, "runtime-jobs": ["cibw", "conda"]})
    )
    jobs = workflow["jobs"]

    # A checkout+runtime job: materialize lands after checkout, before user steps.
    assert [step["name"] for step in jobs["cibw"]["steps"]] == [
        "Checkout repository",
        "Materialize DevFlows runtime scripts",
        "Build wheels",
    ]
    # A checkout+download+runtime job keeps channel order, then materialize.
    assert [step["name"] for step in jobs["conda"]["steps"]] == [
        "Checkout repository",
        "Download artifacts",
        "Materialize DevFlows runtime scripts",
        "Build conda",
    ]


def test_multi_job_permission_seeding_preserves_workflow_grant() -> None:
    # Workflow-level grants only packages: write. Introducing a job-level block for a
    # channel scope must carry that grant along (the fixed seeding semantics).
    jobs = build_published_workflow(
        _multi_job_workflow(workflow_permissions={"packages": "write"})
    )["jobs"]

    assert jobs["cibw"]["permissions"] == {"packages": "write", "contents": "read"}
    assert jobs["conda"]["permissions"] == {
        "packages": "write",
        "contents": "read",
        "actions": "read",
    }


def test_multi_job_checkout_only_inherits_when_workflow_grants_contents() -> None:
    jobs = build_published_workflow(_multi_job_workflow())["jobs"]

    # Workflow-level already grants contents: read, so a checkout-only job keeps
    # inheriting it (no job-level block introduced).
    assert "permissions" not in jobs["cibw"]
    # conda still needs actions: read, which the workflow level lacks -> seeded block.
    assert jobs["conda"]["permissions"] == {"contents": "read", "actions": "read"}


def test_validate_rejects_unknown_checkout_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "dist", "checkout": True, "checkout-jobs": ["ghost"]}},
        {"jobs": {"dist": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any("io.checkout-jobs item 'ghost' must be a runner job" in error for error in errors)


def test_validate_rejects_checkout_job_duplicate_of_io_job() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "dist", "checkout": True, "checkout-jobs": ["dist"]}},
        {"jobs": {"dist": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any("must not also appear in io.checkout-jobs" in error for error in errors)


def test_validate_rejects_download_jobs_without_channel_enabled() -> None:
    item = _make_workflow(
        {"id": "demo", "io": {"job": "dist", "artifact-download-jobs": ["helper"]}},
        {"jobs": {"dist": {"steps": []}, "helper": {"steps": []}}},
    )

    errors = validate_publish_config(item)

    assert any(
        "io.artifact-download-jobs requires io.artifact-download" in error for error in errors
    )


def test_validate_accepts_valid_multi_job_config() -> None:
    item = _make_workflow(
        {
            "id": "demo",
            "io": {
                "job": "dist",
                "checkout": True,
                "artifact-download": True,
                "checkout-jobs": ["cibw"],
                "artifact-download-jobs": ["cibw"],
            },
        },
        {"jobs": {"dist": {"steps": []}, "cibw": {"steps": []}}},
    )

    assert validate_publish_config(item) == []


def test_multi_job_generated_output_snapshot() -> None:
    workflow = build_published_workflow(
        _multi_job_workflow(
            {
                "runtime": True,
                "artifact-upload": True,
                "runtime-jobs": ["cibw", "conda"],
            }
        )
    )
    step_names = {
        job_id: [step["name"] for step in job["steps"]] for job_id, job in workflow["jobs"].items()
    }

    assert step_names == {
        "dist": [
            "Checkout repository",
            "Download artifacts",
            "Materialize DevFlows runtime scripts",
            "Build sdist",
            "Upload artifact",
        ],
        "cibw": [
            "Checkout repository",
            "Materialize DevFlows runtime scripts",
            "Build wheels",
        ],
        "conda": [
            "Checkout repository",
            "Download artifacts",
            "Materialize DevFlows runtime scripts",
            "Build conda",
        ],
    }


def test_render_leaves_uses_line_inside_inlined_script_untouched(make_catalog) -> None:
    from devflows.catalog import load_workflow

    # A script whose body contains a real pinned `uses:` line must survive the
    # dump/annotate pipeline byte-for-byte (no version comment injected), and the
    # integrity check must accept it.
    pin_line = f"# uses: {action_ref('checkout')}\n"
    root = make_catalog(script_body=pin_line + "print('ok')\n")
    import os

    original = Path.cwd()
    try:
        os.chdir(root)
        rendered = render_published_workflow(load_workflow(Path("workflows/demo")))
    finally:
        os.chdir(original)

    assert pin_line.rstrip() in rendered
    assert "# v7.0.0" not in rendered
