from __future__ import annotations

import os
from pathlib import Path

import pytest

from devflows.catalog import Workflow, validate_workflow
from devflows.cli import main


@pytest.fixture(autouse=True)
def _restore_cwd():
    original = Path.cwd()
    try:
        yield
    finally:
        os.chdir(original)


def test_sync_generates_headers_and_inlined_scripts(make_catalog) -> None:
    root = make_catalog()

    assert main(["sync", "--root", str(root)]) == 0

    published = (root / ".github/workflows/demo.yaml").read_text(encoding="utf-8")
    assert published.startswith("# GENERATED by devflows sync")
    assert "source: workflows/demo/" in published
    assert 'cat > "$RUNNER_TEMP/devflows/demo/run.py"' in published
    assert "github.workflow_ref" not in published


def test_validate_reports_count(make_catalog, capsys) -> None:
    root = make_catalog()

    assert main(["validate", "--root", str(root)]) == 0
    assert "validated 1 workflows" in capsys.readouterr().err


def test_validate_fails_outside_catalog(tmp_path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)

    assert main(["validate"]) == 1
    assert "catalog root" in capsys.readouterr().err


def test_sync_fails_on_delimiter_collision(make_catalog, capsys) -> None:
    root = make_catalog(script_body='marker = "DEVFLOWS_SCRIPT_EOF"\n')

    assert main(["sync", "--root", str(root)]) == 1
    assert "delimiter" in capsys.readouterr().err


def test_sync_fails_on_non_ascii_inlined_script(make_catalog, capsys) -> None:
    # A non-ASCII byte forces the YAML dumper to emit the materialize run block
    # as one escaped double-quoted scalar, which GitHub rejects at startup even
    # though actionlint accepts it. Sync must catch it locally instead.
    root = make_catalog(script_body="# blast-radius control — owner only\n")

    assert main(["sync", "--root", str(root)]) == 1
    assert "non-ASCII" in capsys.readouterr().err


def test_sync_check_detects_orphans(make_catalog, capsys) -> None:
    root = make_catalog()
    assert main(["sync", "--root", str(root)]) == 0

    published_dir = root / ".github/workflows"
    (published_dir / "gone.yaml").write_text("name: gone\n", encoding="utf-8")
    (published_dir / "demo").mkdir()  # leftover script directory
    (published_dir / "demo/run.py").write_text("print('stale')\n", encoding="utf-8")

    assert main(["sync", "--check", "--root", str(root)]) == 1
    reported = capsys.readouterr().err
    assert "gone.yaml" in reported
    assert "demo" in reported


def test_sync_prunes_orphans(make_catalog) -> None:
    root = make_catalog()
    assert main(["sync", "--root", str(root)]) == 0
    published_dir = root / ".github/workflows"
    (published_dir / "gone.yaml").write_text("name: gone\n", encoding="utf-8")

    assert main(["sync", "--root", str(root)]) == 0
    assert not (published_dir / "gone.yaml").exists()


def test_sync_check_detects_yml_orphans(make_catalog, capsys) -> None:
    root = make_catalog()
    assert main(["sync", "--root", str(root)]) == 0

    (root / ".github/workflows/legacy.yml").write_text("name: legacy\n", encoding="utf-8")

    assert main(["sync", "--check", "--root", str(root)]) == 1
    assert "legacy.yml" in capsys.readouterr().err


def test_sync_leaves_internal_devflows_files_alone(make_catalog) -> None:
    root = make_catalog()
    assert main(["sync", "--root", str(root)]) == 0
    internal = root / ".github/workflows/devflows-ci.yml"
    internal.write_text("name: internal\n", encoding="utf-8")

    assert main(["sync", "--root", str(root)]) == 0
    assert internal.exists()  # reserved namespace is never pruned


def test_validate_workflow_rejects_reserved_id_prefix() -> None:
    item = Workflow(
        id="devflows-thing",
        path=Path("workflows/devflows-thing"),
        workflow_path=Path("workflows/devflows-thing/workflow.yaml"),
        metadata_path=Path("workflows/devflows-thing/devflow.yaml"),
        metadata={"id": "devflows-thing", "status": "active", "release": {}},
        workflow={"name": "Thing", "on": {"workflow_call": {}}},
    )

    errors = validate_workflow(item)

    assert any("must not start with 'devflows-'" in error for error in errors)


def test_release_check_flags_manifest_major_mismatch(make_catalog, capsys) -> None:
    root = make_catalog()
    manifest = root / ".github/release-please/manifest.json"
    manifest.write_text('{"workflows/demo": "0.3.0"}', encoding="utf-8")

    assert main(["release-check", "--root", str(root)]) == 1
    assert "release.major" in capsys.readouterr().err
