from __future__ import annotations

import os
from pathlib import Path

import pytest

from devflows.cli import main


@pytest.fixture(autouse=True)
def _restore_cwd():
    original = Path.cwd()
    try:
        yield
    finally:
        os.chdir(original)


def test_sync_generates_headers_and_inlined_scripts(make_catalog) -> None:
    root = make_catalog()

    assert main(["sync", "--root", str(root)]) == 0

    published = (root / ".github/workflows/demo.yaml").read_text(encoding="utf-8")
    assert published.startswith("# GENERATED by devflows sync")
    assert "source: workflows/demo/" in published
    assert 'cat > "$RUNNER_TEMP/devflows/demo/run.py"' in published
    assert "github.workflow_ref" not in published


def test_validate_reports_count(make_catalog, capsys) -> None:
    root = make_catalog()

    assert main(["validate", "--root", str(root)]) == 0
    assert "validated 1 workflows" in capsys.readouterr().err


def test_validate_fails_outside_catalog(tmp_path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)

    assert main(["validate"]) == 1
    assert "catalog root" in capsys.readouterr().err


def test_sync_fails_on_delimiter_collision(make_catalog, capsys) -> None:
    root = make_catalog(script_body='marker = "DEVFLOWS_SCRIPT_EOF"\n')

    assert main(["sync", "--root", str(root)]) == 1
    assert "delimiter" in capsys.readouterr().err


def test_sync_check_detects_orphans(make_catalog, capsys) -> None:
    root = make_catalog()
    assert main(["sync", "--root", str(root)]) == 0

    published_dir = root / ".github/workflows"
    (published_dir / "gone.yaml").write_text("name: gone\n", encoding="utf-8")
    (published_dir / "demo").mkdir()  # leftover script directory
    (published_dir / "demo/run.py").write_text("print('stale')\n", encoding="utf-8")

    assert main(["sync", "--check", "--root", str(root)]) == 1
    reported = capsys.readouterr().err
    assert "gone.yaml" in reported
    assert "demo" in reported


def test_sync_prunes_orphans(make_catalog) -> None:
    root = make_catalog()
    assert main(["sync", "--root", str(root)]) == 0
    published_dir = root / ".github/workflows"
    (published_dir / "gone.yaml").write_text("name: gone\n", encoding="utf-8")

    assert main(["sync", "--root", str(root)]) == 0
    assert not (published_dir / "gone.yaml").exists()


def test_release_check_flags_manifest_major_mismatch(make_catalog, capsys) -> None:
    root = make_catalog()
    manifest = root / ".github/release-please/manifest.json"
    manifest.write_text('{"workflows/demo": "0.3.0"}', encoding="utf-8")

    assert main(["release-check", "--root", str(root)]) == 1
    assert "release.major" in capsys.readouterr().err
