from __future__ import annotations

from pathlib import Path
from typing import Any

from devflows.catalog import Workflow
from devflows.errors import DevflowsError
from devflows.project import Project, load_project
from devflows.publish import build_published_workflow, caller_required_permissions

GENERATED_DIR = Path("docs/reference")


def _header(source: str) -> str:
    return f"<!-- GENERATED by devflows docs — do not edit; source: {source} -->"


def render_catalog(workflows: list[Workflow]) -> str:
    lines = [
        _header("workflows/"),
        "",
        "# Workflow Catalog",
        "",
        "This page is generated from the workflow catalog metadata.",
        "",
        "```{toctree}",
        ":maxdepth: 1",
        "",
    ]
    lines.extend(f"workflows/{item.id}" for item in workflows)
    lines.extend(["```", ""])
    return "\n".join(lines)


def render_workflow(item: Workflow, project: Project | None = None) -> str:
    if project is None:
        project = load_project()
    published_workflow = build_published_workflow(item)
    workflow_call = _workflow_call(published_workflow)
    inputs = _mapping(workflow_call.get("inputs"))
    secrets = _mapping(workflow_call.get("secrets"))
    outputs = _mapping(workflow_call.get("outputs"))
    # The union of workflow-level and every job-level permission block: the exact
    # superset a caller must grant, because GitHub validates a reusable-workflow
    # call against that union at startup (job-level blocks replace the top level).
    required_permissions = caller_required_permissions(published_workflow)
    examples = item.metadata.get("examples") or []
    release = item.metadata.get("release") or {}
    notes = item.metadata.get("notes") or []
    scenarios = item.metadata.get("tests", {}).get("scenarios", []) or []
    major = release.get("major", 0)
    if major >= 1:
        # Post-1.0: moving major tags are published and are the recommended
        # convenience reference.
        usage_ref = project.uses_reference(item.id, f"{item.id}/v{major}")
        versioning_lines = [
            f"- Current line: `{item.id}/v{major}` (moving major tag).",
            f"- Exact release tags use `{item.id}/vX.Y.Z`.",
            "- Commit SHAs remain the highest-assurance reference.",
        ]
    else:
        # Pre-1.0 (0.x): no moving major tag exists yet, so pin an exact release
        # tag or a commit SHA. Moving major tags activate at the 1.0 release.
        usage_ref = project.uses_reference(item.id, f"{item.id}/vX.Y.Z")
        versioning_lines = [
            "- Status: pre-1.0 (0.x). Pin an exact release tag or a commit SHA.",
            f"- Exact release tags use `{item.id}/vX.Y.Z`.",
            f"- Moving major tags (`{item.id}/vN`) begin at the 1.0 release.",
            "- Commit SHAs remain the highest-assurance reference.",
        ]

    lines = [
        _header(f"workflows/{item.id}/"),
        "",
        f"# {item.name}",
        "",
        item.summary or "No summary provided.",
        "",
        "## Usage",
        "",
        "```yaml",
        "jobs:",
        f"  call-{item.id}:",
        f"    uses: {usage_ref}",
        "```",
        "",
        "## Versioning",
        "",
        *versioning_lines,
        "",
        "## Inputs",
        "",
        _render_table(inputs, ["name", "type", "required", "default", "description"]),
        "",
        "## Secrets",
        "",
        _render_table(secrets, ["name", "required", "description"]),
        "",
        "## Outputs",
        "",
        _render_table(outputs, ["name", "description"]),
        "",
        "## Permissions",
        "",
        _render_permissions(required_permissions),
        "",
        "## Examples",
        "",
    ]
    if examples:
        for example in examples:
            title = example.get("name", "Example")
            path = example.get("path", "")
            lines.extend([f"### {title}", "", f"Source: `{path}`", ""])
            if path:
                lines.extend(["```yaml", _read_example(path), "```", ""])
    else:
        lines.append("No examples registered yet.")
        lines.append("")
    if notes:
        lines.extend(["## Notes", ""])
        lines.extend(f"- {note}" for note in notes)
        lines.append("")
    if scenarios:
        lines.extend(["## Test Scenarios", ""])
        for scenario in scenarios:
            scenario_id = scenario.get("id", "")
            scenario_name = scenario.get("name") or scenario_id
            runs = ", ".join(scenario.get("runs", []) or [])
            assertions = scenario.get("assertions", []) or []
            lines.append(
                f"- `{scenario_id}`: {scenario_name} ({runs}); {len(assertions)} assertion(s)."
            )
        lines.append("")
    return "\n".join(lines)


def _workflow_call(workflow: dict[str, Any]) -> dict[str, Any]:
    on_block = workflow.get("on") or {}
    if not isinstance(on_block, dict):
        return {}
    workflow_call = on_block.get("workflow_call") or {}
    return workflow_call if isinstance(workflow_call, dict) else {}


def write_generated_docs(
    workflows: list[Workflow],
    *,
    check: bool = False,
    output_dir: Path = GENERATED_DIR,
) -> list[Path]:
    project = load_project()
    outputs = {
        output_dir / "catalog.md": render_catalog(workflows),
        **{
            output_dir / "workflows" / f"{item.id}.md": render_workflow(item, project)
            for item in workflows
        },
    }
    changed: list[Path] = []
    for path, content in outputs.items():
        normalized = content.rstrip() + "\n"
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != normalized:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(normalized, encoding="utf-8")
    return changed


def _mapping(value: Any) -> dict[str, dict[str, Any]]:
    if not isinstance(value, dict):
        return {}
    return {str(key): data if isinstance(data, dict) else {} for key, data in value.items()}


def _render_table(items: dict[str, dict[str, Any]], columns: list[str]) -> str:
    if not items:
        return "None."
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for name, data in items.items():
        row = []
        for column in columns:
            value = name if column == "name" else data.get(column, "")
            row.append(_cell(value))
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _render_permissions(permissions: Any) -> str:
    if not permissions:
        return "No caller permissions required."
    if isinstance(permissions, str):
        return f"`{permissions}`"
    if isinstance(permissions, dict):
        lines = [
            "Required caller permissions (the union of this workflow's top-level and "
            "per-job permission blocks; a calling job must grant at least these):",
            "",
        ]
        lines.extend(f"- `{name}`: `{value}`" for name, value in sorted(permissions.items()))
        return "\n".join(lines)
    return str(permissions)


def _read_example(path: str) -> str:
    example_path = Path(path)
    if not example_path.is_file():
        raise DevflowsError(f"example fixture does not exist: {path}")
    return example_path.read_text(encoding="utf-8").rstrip()


def _cell(value: Any) -> str:
    if value is None:
        return ""
    text = str(value).replace("\n", "<br>")
    return text.replace("|", "\\|")
