from __future__ import annotations

import re
from copy import deepcopy
from pathlib import Path, PurePosixPath
from typing import Any

from devflows.actions import annotate_pins
from devflows.actions import ref as action_ref
from devflows.catalog import CATALOG_DIR, Workflow
from devflows.errors import DevflowsError
from devflows.yaml import dump_yaml, load_yaml_text

# At sync time each workflow's runtime scripts are inlined into the generated
# YAML (rather than checked out from the DevFlows repo at run time, which broke
# cross-repo consumers because github.workflow_ref is the caller's ref). The
# materialize step writes each script to $RUNNER_TEMP/devflows/<path> via a
# single-quoted heredoc so the body is emitted verbatim with no shell expansion.
RUNTIME_SCRIPT_DELIMITER = "DEVFLOWS_SCRIPT_EOF"
RUNTIME_SCRIPT_ROOT = "$RUNNER_TEMP/devflows"
_SCRIPT_REF_PATTERN = re.compile(r"\$\{DEVFLOWS_SCRIPT_ROOT\}/([A-Za-z0-9_./-]+\.py)")

GENERATED_HEADER_TEMPLATE = "# GENERATED by devflows sync — do not edit; source: workflows/{id}/\n"

# Levels a caller can grant a nested reusable-workflow call, ranked so the required
# permissions are the maximum requested anywhere in the called workflow tree.
_PERMISSION_RANK = {"none": 0, "read": 1, "write": 2}


def caller_required_permissions(published: dict[str, Any]) -> dict[str, str]:
    """Union of the permissions a published workflow requires from its caller.

    GitHub validates a reusable-workflow call's granted permissions against the
    superset of every permission the called workflow declares — its top-level block
    plus each job's block (job-level blocks replace, not merge with, the top-level
    grant). Returning that union (max rank per scope, ``none`` dropped, sorted)
    gives the exact set a caller must grant, which docs render and the internal /
    example caller tests assert against.
    """
    merged: dict[str, str] = {}
    sources: list[Any] = [published.get("permissions")]
    for job in (published.get("jobs") or {}).values():
        if isinstance(job, dict):
            sources.append(job.get("permissions"))
    for perms in sources:
        if not isinstance(perms, dict):
            continue
        for name, level in perms.items():
            level_str = str(level)
            current = merged.get(name, "none")
            if _PERMISSION_RANK.get(level_str, 0) > _PERMISSION_RANK.get(current, 0):
                merged[name] = level_str
    return {name: level for name, level in sorted(merged.items()) if level != "none"}


def render_published_workflow(item: Workflow) -> str:
    header = GENERATED_HEADER_TEMPLATE.format(id=item.id)
    if not _io_config(item):
        body = item.workflow_path.read_text(encoding="utf-8")
    else:
        body = dump_yaml(build_published_workflow(item))
    rendered = header + annotate_pins(body)
    _assert_inlined_scripts_intact(item, rendered)
    return rendered


_HEREDOC_OPEN = re.compile(
    rf'^\s*cat > "{re.escape(RUNTIME_SCRIPT_ROOT)}/(?P<relpath>[^"]+)"'
    rf" <<'{re.escape(RUNTIME_SCRIPT_DELIMITER)}'$"
)


def _extract_heredoc_bodies(run: str) -> dict[str, str]:
    """Map each inlined script's relpath to its heredoc body in a materialize run."""
    bodies: dict[str, str] = {}
    lines = run.splitlines()
    index = 0
    while index < len(lines):
        match = _HEREDOC_OPEN.match(lines[index])
        if not match:
            index += 1
            continue
        relpath = match.group("relpath")
        index += 1
        body_lines: list[str] = []
        while index < len(lines) and lines[index] != RUNTIME_SCRIPT_DELIMITER:
            body_lines.append(lines[index])
            index += 1
        bodies[relpath] = "\n".join(body_lines)
        index += 1  # skip the closing delimiter
    return bodies


def _assert_inlined_scripts_intact(item: Workflow, rendered: str) -> None:
    """Fail if the full dump/annotate pipeline altered any inlined script body.

    ``annotate_pins`` and the YAML dumper both operate on text, so a regression
    could rewrite a line *inside* an inlined heredoc (e.g. a script that contains
    the literal ``uses: <action>@<sha>``). Re-parse the rendered workflow and
    confirm every materialized body still byte-matches its catalog source.
    """
    if not _io_config(item):
        return
    workflow = load_yaml_text(rendered)
    for job in (workflow.get("jobs") or {}).values():
        if not isinstance(job, dict):
            continue
        for step in job.get("steps", []) or []:
            if not isinstance(step, dict) or step.get("id") != "devflows-runtime":
                continue
            run = step.get("run")
            if not isinstance(run, str):
                continue
            for relpath, body in _extract_heredoc_bodies(run).items():
                expected = (
                    _source_script_path(item, relpath).read_text(encoding="utf-8").rstrip("\n")
                )
                if body != expected:
                    raise DevflowsError(
                        f"{item.metadata_path}: inlined runtime script {relpath!r} does not "
                        "byte-match its catalog source after rendering. The dump/annotate "
                        "pipeline corrupted the heredoc body."
                    )


def build_published_workflow(item: Workflow) -> dict[str, Any]:
    workflow = deepcopy(item.workflow)
    io_config = _io_config(item)
    if not io_config:
        return workflow

    workflow_call = _workflow_call(workflow)
    inputs = workflow_call.setdefault("inputs", {})
    secrets = workflow_call.setdefault("secrets", {})

    if _enabled(io_config, "checkout"):
        inputs.update(deepcopy(CHECKOUT_INPUTS))
        secrets.update(deepcopy(CHECKOUT_SECRETS))
    if _enabled(io_config, "artifact-download"):
        inputs.update(deepcopy(ARTIFACT_DOWNLOAD_INPUTS))
        secrets.update(deepcopy(ARTIFACT_DOWNLOAD_SECRETS))
    if _enabled(io_config, "artifact-upload"):
        inputs.update(deepcopy(ARTIFACT_UPLOAD_INPUTS))
    if _enabled(io_config, "writeback"):
        inputs.update(deepcopy(COMMIT_INPUTS))
        # Run-scope the default so two commit-enabled invocations of the same
        # workflow across different runs cannot clobber each other's payload
        # (the upload step uses overwrite: true). Reusable-workflow input
        # defaults may reference the github context. Multiple invocations within
        # a single run still need distinct caller-provided names (see description).
        inputs["commit-internal-artifact-name"]["default"] = (
            f"devflows-{item.id}-writeback-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}"
        )
        secrets.update(deepcopy(COMMIT_SECRETS))

    job_id = str(io_config.get("job") or _first_runner_job_id(workflow))
    jobs = workflow.setdefault("jobs", {})
    if job_id not in jobs:
        raise ValueError(f"{item.metadata_path}: io.job {job_id!r} does not exist.")
    job = jobs[job_id]
    if not isinstance(job, dict) or "steps" not in job:
        raise ValueError(f"{item.metadata_path}: io.job {job_id!r} must be a runner job.")

    prefix_steps: list[dict[str, Any]] = []
    suffix_steps: list[dict[str, Any]] = []
    if _enabled(io_config, "checkout"):
        prefix_steps.append(_checkout_step())
    if _enabled(io_config, "artifact-download"):
        prefix_steps.append(_download_artifact_step())
    if _enabled(io_config, "artifact-upload"):
        suffix_steps.append(_upload_artifact_step())
    if _enabled(io_config, "writeback"):
        suffix_steps.extend(_create_writeback_steps())
        jobs["commit"] = _commit_job(job_id)

    original_steps = list(job.get("steps", []))
    assembled = prefix_steps + original_steps + suffix_steps
    if _enabled(io_config, "runtime"):
        # Materialize after checkout/download (which never reference scripts) and
        # before the domain steps that invoke them.
        assembled.insert(len(prefix_steps), _materialize_step(item, assembled))
    job["steps"] = assembled

    workflow_permissions_raw = workflow.get("permissions")
    workflow_permissions = (
        workflow_permissions_raw if isinstance(workflow_permissions_raw, dict) else {}
    )

    # Inject the checkout / artifact-download / runtime channel steps into every
    # additional job that asks for them (io.checkout-jobs, io.artifact-download-jobs,
    # io.runtime-jobs). python-build's cibw/conda matrix jobs, for example, each need
    # the checked-out source (checkout-jobs) *and* the DevFlows scripts (runtime-jobs).
    # A job may appear in several lists; process it once, emitting the same channel
    # steps in the same relative order as io.job (checkout, download, then materialize
    # before any user step).
    checkout_job_ids = _channel_job_ids(io_config, "checkout-jobs")
    download_job_ids = _channel_job_ids(io_config, "artifact-download-jobs")
    runtime_job_ids = _runtime_job_ids(io_config)
    for extra_job_id in _ordered_unique([*checkout_job_ids, *download_job_ids, *runtime_job_ids]):
        # io.job is already fully handled above; validation forbids listing it again.
        if extra_job_id == job_id:
            continue
        extra_job = jobs.get(extra_job_id)
        if not isinstance(extra_job, dict) or "steps" not in extra_job:
            raise ValueError(
                f"{item.metadata_path}: io channel job {extra_job_id!r} must be a runner job."
            )
        inject_checkout = extra_job_id in checkout_job_ids and _enabled(io_config, "checkout")
        inject_download = extra_job_id in download_job_ids and _enabled(
            io_config, "artifact-download"
        )
        inject_runtime = extra_job_id in runtime_job_ids
        extra_prefix: list[dict[str, Any]] = []
        if inject_checkout:
            extra_prefix.append(_checkout_step())
        if inject_download:
            extra_prefix.append(_download_artifact_step())
        extra_assembled = extra_prefix + list(extra_job.get("steps", []))
        if inject_runtime:
            # Materialize after checkout/download and before the domain steps, exactly
            # as io.job does.
            extra_assembled.insert(len(extra_prefix), _materialize_step(item, extra_assembled))
        extra_job["steps"] = extra_assembled
        _ensure_job_permissions(
            extra_job,
            workflow_permissions,
            contents="read" if inject_checkout else None,
            actions="read" if inject_download else None,
        )

    _ensure_job_permissions(
        job,
        workflow_permissions,
        contents="read",
        actions="read"
        if any(
            _enabled(io_config, channel)
            for channel in ("artifact-download", "artifact-upload", "writeback")
        )
        else None,
    )
    return workflow


def validate_publish_config(item: Workflow) -> list[str]:
    errors: list[str] = []
    config = _io_config(item)
    if not config:
        return errors
    supported = {
        "artifact-download",
        "artifact-download-jobs",
        "artifact-upload",
        "checkout",
        "checkout-jobs",
        "job",
        "runtime",
        "writeback",
        "runtime-jobs",
    }
    for key in config:
        if key not in supported:
            errors.append(f"{item.metadata_path}: io.{key} is not supported.")
    if _enabled(config, "writeback") and not _enabled(config, "runtime"):
        errors.append(f"{item.metadata_path}: io.writeback requires io.runtime.")
    job_id = str(config.get("job") or "")
    jobs = item.workflow.get("jobs") or {}
    if job_id:
        job = jobs.get(job_id)
        if not isinstance(job, dict) or "steps" not in job:
            errors.append(f"{item.metadata_path}: io.job {job_id!r} must be a runner job.")
    elif not any(isinstance(job, dict) and "steps" in job for job in jobs.values()):
        errors.append(f"{item.metadata_path}: io requires at least one runner job.")
    # runtime-jobs, checkout-jobs, and artifact-download-jobs all name additional jobs
    # that receive a generator-injected channel step; they share the same shape rules
    # (list of existing runner jobs, none equal to io.job — see _validate_channel_jobs).
    runtime_errors, runtime_job_ids = _validate_channel_jobs(
        item, config, jobs, job_id, "runtime-jobs"
    )
    errors.extend(runtime_errors)
    checkout_errors, checkout_job_ids = _validate_channel_jobs(
        item, config, jobs, job_id, "checkout-jobs"
    )
    errors.extend(checkout_errors)
    download_errors, download_job_ids = _validate_channel_jobs(
        item, config, jobs, job_id, "artifact-download-jobs"
    )
    errors.extend(download_errors)
    # A channel-jobs list injects a step that references the channel's public inputs,
    # which only exist when the channel itself is enabled. Requiring the channel keeps
    # the generated step from referencing inputs the workflow never declared.
    if checkout_job_ids and not _enabled(config, "checkout"):
        errors.append(f"{item.metadata_path}: io.checkout-jobs requires io.checkout.")
    if download_job_ids and not _enabled(config, "artifact-download"):
        errors.append(
            f"{item.metadata_path}: io.artifact-download-jobs requires io.artifact-download."
        )
    # Every job that runs a ${DEVFLOWS_SCRIPT_ROOT}/ script must receive the
    # materialize step, i.e. be io.job or a runtime-job. Otherwise script-root is
    # never exported for it and the step fails at runtime with an empty path.
    if _enabled(config, "runtime"):
        resolved_job_id = job_id or _safe_first_runner_job_id(jobs)
        script_capable = {resolved_job_id, *runtime_job_ids}
        for candidate_id, candidate in jobs.items():
            if not isinstance(candidate, dict):
                continue
            if _job_references_script_root(candidate) and str(candidate_id) not in script_capable:
                errors.append(
                    f"{item.metadata_path}: job {candidate_id!r} references "
                    "${DEVFLOWS_SCRIPT_ROOT} but is neither io.job nor listed in "
                    "io.runtime-jobs, so no materialize step exports script-root for it."
                )
    return errors


def _validate_channel_jobs(
    item: Workflow,
    config: dict[str, Any],
    jobs: dict[str, Any],
    job_id: str,
    key: str,
) -> tuple[list[str], list[str]]:
    """Validate an io channel-jobs list (runtime/checkout/artifact-download).

    Each named job must exist as a runner job, and none may repeat io.job — both
    the io.job path and the channel-jobs path inject the same channel steps, so
    listing io.job again would duplicate them (the "devflows-runtime" materialize
    step even collides on its step id). Returns (errors, job_ids).
    """
    errors: list[str] = []
    raw = config.get(key, []) or []
    if not isinstance(raw, list):
        errors.append(f"{item.metadata_path}: io.{key} must be a list.")
        return errors, []
    channel_job_ids = [str(channel_job_id) for channel_job_id in raw]
    for channel_job_id in channel_job_ids:
        job = jobs.get(channel_job_id)
        if not isinstance(job, dict) or "steps" not in job:
            errors.append(
                f"{item.metadata_path}: io.{key} item {channel_job_id!r} must be a runner job."
            )
    if job_id and job_id in channel_job_ids:
        errors.append(f"{item.metadata_path}: io.job {job_id!r} must not also appear in io.{key}.")
    return errors, channel_job_ids


def _safe_first_runner_job_id(jobs: dict[str, Any]) -> str:
    for candidate_id, candidate in jobs.items():
        if isinstance(candidate, dict) and "steps" in candidate:
            return str(candidate_id)
    return ""


def _job_references_script_root(job: dict[str, Any]) -> bool:
    """Whether any step in ``job`` reads the DevFlows runtime script root."""
    for step in job.get("steps", []) or []:
        if not isinstance(step, dict):
            continue
        run = step.get("run")
        if isinstance(run, str) and "DEVFLOWS_SCRIPT_ROOT" in run:
            return True
        env = step.get("env")
        if isinstance(env, dict):
            for value in env.values():
                if isinstance(value, str) and "devflows-runtime" in value:
                    return True
    return False


def published_workflow_call(item: Workflow) -> dict[str, Any]:
    workflow_call = _workflow_call(build_published_workflow(item))
    return workflow_call if isinstance(workflow_call, dict) else {}


def write_published_workflow(path: Path, item: Workflow) -> None:
    path.write_text(render_published_workflow(item).rstrip() + "\n", encoding="utf-8")


def _workflow_call(workflow: dict[str, Any]) -> dict[str, Any]:
    on_block = workflow.setdefault("on", {})
    if not isinstance(on_block, dict):
        raise ValueError("workflow on block must be a mapping.")
    workflow_call = on_block.setdefault("workflow_call", {})
    if not isinstance(workflow_call, dict):
        raise ValueError("workflow_call block must be a mapping.")
    return workflow_call


def _io_config(item: Workflow) -> dict[str, Any]:
    config = item.metadata.get("io") or {}
    if config is True:
        return {"checkout": True, "artifact-download": True, "artifact-upload": True}
    if not isinstance(config, dict):
        return {}
    return config


def _enabled(config: dict[str, Any], name: str) -> bool:
    return bool(config.get(name))


def _runtime_job_ids(config: dict[str, Any]) -> list[str]:
    return _channel_job_ids(config, "runtime-jobs")


def _channel_job_ids(config: dict[str, Any], key: str) -> list[str]:
    """The job ids listed under an io channel-jobs key (runtime/checkout/download)."""
    raw = config.get(key, []) or []
    if not isinstance(raw, list):
        return []
    return [str(item) for item in raw]


def _ordered_unique(items: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            ordered.append(item)
    return ordered


def _first_runner_job_id(workflow: dict[str, Any]) -> str:
    jobs = workflow.get("jobs") or {}
    for job_id, job in jobs.items():
        if isinstance(job, dict) and "steps" in job:
            return str(job_id)
    raise ValueError("workflow must contain at least one runner job for IO injection.")


def _ensure_job_permissions(
    job: dict[str, Any],
    workflow_permissions: dict[str, Any],
    **permissions: str | None,
) -> None:
    """Grant a job the permissions the injected IO channels need.

    GitHub job-level permissions *replace* the workflow-level grant rather than
    merge with it, so a job that declares its own ``permissions`` block no longer
    inherits any workflow-level scope. Two consequences drive this logic:

    * When a job declares no permissions block it inherits the workflow-level
      grant. If every channel permission is already satisfied by that grant we
      leave the block absent so inheritance keeps working. Only when a channel
      needs a scope the workflow level does not provide must we introduce a
      job-level block — and then we seed the full workflow-level map first, or
      the newly-introduced block would silently drop the workflow's grants (the
      reproduced case: workflow-level ``packages: write`` vanishing from an io
      job that only asked for ``contents: read``).
    * A job that already declares its own permissions block is authoritative;
      we only add channel scopes it is missing and never remove a key the source
      declared explicitly (including an author-written ``permissions: {}``).
    """
    requested = {name: level for name, level in permissions.items() if level is not None}
    existing = job.get("permissions")
    if isinstance(existing, dict):
        for name, level in requested.items():
            existing.setdefault(name, level)
        return
    if "permissions" in job:
        # Author wrote a non-mapping permissions value (e.g. null); leave intent.
        return
    missing = {
        name: level
        for name, level in requested.items()
        if str(workflow_permissions.get(name) or "") != level
    }
    if not missing:
        return
    seeded = dict(workflow_permissions)
    seeded.update(missing)
    job["permissions"] = seeded


def _checkout_step() -> dict[str, Any]:
    return {
        "name": "Checkout repository",
        "if": "inputs.checkout-enabled",
        "uses": action_ref("checkout"),
        "with": {
            "repository": "${{ inputs.checkout-repository }}",
            "ref": "${{ inputs.checkout-ref }}",
            "token": "${{ secrets.checkout-token || github.token }}",
            "ssh-key": "${{ secrets.checkout-ssh-key }}",
            "ssh-known-hosts": "${{ inputs.checkout-ssh-known-hosts }}",
            "ssh-strict": "${{ inputs.checkout-ssh-strict }}",
            "ssh-user": "${{ inputs.checkout-ssh-user }}",
            "persist-credentials": "${{ inputs.checkout-persist-credentials }}",
            "path": "${{ inputs.checkout-path }}",
            "clean": "${{ inputs.checkout-clean }}",
            "filter": "${{ inputs.checkout-filter }}",
            "sparse-checkout": "${{ inputs.checkout-sparse-checkout }}",
            "sparse-checkout-cone-mode": "${{ inputs.checkout-sparse-checkout-cone-mode }}",
            "fetch-depth": "${{ inputs.checkout-fetch-depth }}",
            "fetch-tags": "${{ inputs.checkout-fetch-tags }}",
            "show-progress": "${{ inputs.checkout-show-progress }}",
            "lfs": "${{ inputs.checkout-lfs }}",
            "submodules": "${{ inputs.checkout-submodules }}",
            "set-safe-directory": "${{ inputs.checkout-set-safe-directory }}",
            "github-server-url": "${{ inputs.checkout-github-server-url }}",
            "allow-unsafe-pr-checkout": "${{ inputs.checkout-allow-unsafe-pr-checkout }}",
        },
    }


def _download_artifact_step() -> dict[str, Any]:
    return {
        "name": "Download artifacts",
        "if": "inputs.artifact-download-enabled",
        "uses": action_ref("download-artifact"),
        "with": {
            "name": "${{ inputs.artifact-download-name }}",
            "artifact-ids": "${{ inputs.artifact-download-ids }}",
            "path": "${{ inputs.artifact-download-path }}",
            "pattern": "${{ inputs.artifact-download-pattern }}",
            "merge-multiple": "${{ inputs.artifact-download-merge-multiple }}",
            "github-token": "${{ secrets.artifact-download-token }}",
            "repository": "${{ inputs.artifact-download-repository }}",
            "run-id": "${{ inputs.artifact-download-run-id }}",
            "skip-decompress": "${{ inputs.artifact-download-skip-decompress }}",
            "digest-mismatch": "${{ inputs.artifact-download-digest-mismatch }}",
        },
    }


def _referenced_scripts(steps: list[dict[str, Any]]) -> list[str]:
    """Relative script paths referenced via ${DEVFLOWS_SCRIPT_ROOT}/... in run blocks."""
    seen: list[str] = []
    for step in steps:
        run = step.get("run")
        if not isinstance(run, str):
            continue
        for match in _SCRIPT_REF_PATTERN.finditer(run):
            relpath = match.group(1)
            if relpath not in seen:
                seen.append(relpath)
    return seen


def _source_script_path(item: Workflow, relpath: str) -> Path:
    """Map a published script reference (e.g. `pandoc/run-pandoc.py`) to its source."""
    workflow_id, _, rest = relpath.partition("/")
    if not rest:
        raise DevflowsError(
            f"{item.metadata_path}: runtime script reference {relpath!r} must be "
            "of the form <workflow-id>/<script>."
        )
    source = CATALOG_DIR / workflow_id / "scripts" / rest
    if not source.is_file():
        raise DevflowsError(
            f"{item.metadata_path}: runtime script {relpath!r} not found at {source}."
        )
    return source


def _materialize_step(item: Workflow, steps: list[dict[str, Any]]) -> dict[str, Any]:
    """Build a step that writes referenced scripts to $RUNNER_TEMP/devflows/<path>."""
    lines = ["set -euo pipefail"]
    for relpath in _referenced_scripts(steps):
        source = _source_script_path(item, relpath)
        content = source.read_text(encoding="utf-8")
        if RUNTIME_SCRIPT_DELIMITER in content:
            raise DevflowsError(
                f"{source}: script contains the heredoc delimiter "
                f"{RUNTIME_SCRIPT_DELIMITER!r}, so it cannot be inlined safely."
            )
        # Inlined scripts must be ASCII. A single non-ASCII byte makes the YAML
        # dumper render the whole materialize `run:` block as one escaped
        # double-quoted scalar instead of a block literal; GitHub's workflow
        # parser rejects that collapsed form with a startup failure even though
        # actionlint's parser accepts it, so the drift is invisible to `task
        # lint` and only surfaces on a hosted run. Fail loudly at sync time
        # instead, pointing at the offending line.
        try:
            content.encode("ascii")
        except UnicodeEncodeError as error:
            line_number = content[: error.start].count("\n") + 1
            raise DevflowsError(
                f"{source}:{line_number}: inlined runtime script contains a "
                f"non-ASCII character ({content[error.start]!r}). Inlined scripts "
                "must be ASCII so they render as YAML block literals; replace it "
                "(e.g. an em-dash with '--')."
            ) from error
        target = f"{RUNTIME_SCRIPT_ROOT}/{relpath}"
        directory = PurePosixPath(target).parent.as_posix()
        lines.append(f'mkdir -p "{directory}"')
        lines.append(f"cat > \"{target}\" <<'{RUNTIME_SCRIPT_DELIMITER}'")
        lines.append(content.rstrip("\n"))
        lines.append(RUNTIME_SCRIPT_DELIMITER)
    lines.append(f'echo "script-root={RUNTIME_SCRIPT_ROOT}" >> "$GITHUB_OUTPUT"')
    return {
        "name": "Materialize DevFlows runtime scripts",
        "id": "devflows-runtime",
        "shell": "bash",
        "run": "\n".join(lines),
    }


def _upload_artifact_step() -> dict[str, Any]:
    return {
        "name": "Upload artifact",
        "if": "inputs.artifact-upload-enabled && inputs.artifact-upload-path != ''",
        "uses": action_ref("upload-artifact"),
        "with": {
            "name": "${{ inputs.artifact-upload-name }}",
            "path": "${{ inputs.artifact-upload-path }}",
            "if-no-files-found": "${{ inputs.artifact-upload-if-no-files-found }}",
            "retention-days": "${{ inputs.artifact-upload-retention-days }}",
            "compression-level": "${{ inputs.artifact-upload-compression-level }}",
            "overwrite": "${{ inputs.artifact-upload-overwrite }}",
            "include-hidden-files": "${{ inputs.artifact-upload-include-hidden-files }}",
            "archive": "${{ inputs.artifact-upload-archive }}",
        },
    }


def _create_writeback_steps() -> list[dict[str, Any]]:
    return [
        {
            "name": "Create writeback payload",
            "if": "inputs.commit-enabled",
            "env": {
                "DEVFLOWS_SCRIPT_ROOT": "${{ steps.devflows-runtime.outputs.script-root }}",
                "WRITEBACK_DELETE_PATHS": "${{ inputs.commit-delete-paths }}",
                "WRITEBACK_PATHS": "${{ inputs.commit-paths }}",
                "WRITEBACK_PAYLOAD_DIR": ".devflows-writeback/payload",
                "WRITEBACK_SOURCE_REF": "${{ github.ref }}",
                "WRITEBACK_SOURCE_REPOSITORY": "${{ github.repository }}",
                "WRITEBACK_SOURCE_SHA": "${{ github.sha }}",
            },
            "shell": "bash",
            "run": 'python "${DEVFLOWS_SCRIPT_ROOT}/writeback/create-payload.py"',
        },
        {
            "name": "Upload writeback payload",
            "if": "inputs.commit-enabled",
            "uses": action_ref("upload-artifact"),
            "with": {
                "name": "${{ inputs.commit-internal-artifact-name }}",
                "path": ".devflows-writeback/payload",
                "if-no-files-found": "error",
                "retention-days": 1,
                "compression-level": 0,
                "overwrite": True,
                "include-hidden-files": True,
            },
        },
    ]


def _commit_job(needs: str) -> dict[str, Any]:
    # This nested reusable-workflow call uses a relative ref. Per GitHub's
    # documentation ("Reuse workflows"): a workflow called without {owner}/{repo}
    # and @{ref} "is from the same commit as the caller workflow" — here the caller
    # is the file containing this uses (e.g. pandoc.yaml), not the top-level
    # consumer. So when a consumer calls pandoc.yaml@<devflows-sha> cross-repo, this
    # resolves to writeback.yaml at that same devflows repo+SHA, caller-independent.
    # (This differs from composite-action `./` refs, which resolve against the
    # caller's checked-out workspace; secondary sources sometimes conflate the two.)
    # Verified against docs.github.com/actions/.../reuse-workflows, 2026-07.
    return {
        "name": "Commit generated files",
        "needs": needs,
        "if": "inputs.commit-enabled",
        "uses": "./.github/workflows/writeback.yaml",
        "permissions": {"actions": "read", "contents": "write"},
        "with": {
            "writeback-artifact-name": "${{ inputs.commit-internal-artifact-name }}",
            "commit-repository": "${{ inputs.commit-repository }}",
            "commit-branch": "${{ inputs.commit-branch }}",
            "commit-message": "${{ inputs.commit-message }}",
            "commit-author-name": "${{ inputs.commit-author-name }}",
            "commit-author-email": "${{ inputs.commit-author-email }}",
            "commit-push": "${{ inputs.commit-push }}",
            "commit-expected-base-sha": "${{ inputs.commit-expected-base-sha }}",
        },
        "secrets": {"commit-token": "${{ secrets.commit-token }}"},
    }


CHECKOUT_INPUTS: dict[str, dict[str, Any]] = {
    "checkout-enabled": {
        "description": "Whether to run actions/checkout before workflow execution.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-repository": {
        "description": "Repository name with owner to checkout.",
        "type": "string",
        "required": False,
        "default": "${{ github.repository }}",
    },
    "checkout-ref": {
        "description": "Branch, tag, or SHA to checkout.",
        "type": "string",
        "required": False,
        "default": "${{ github.ref }}",
    },
    "checkout-ssh-known-hosts": {
        "description": "Known hosts in addition to the user and global host key database.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-ssh-strict": {
        "description": "Whether to perform strict host key checking.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-ssh-user": {
        "description": "SSH user to use when connecting to the remote SSH host.",
        "type": "string",
        "required": False,
        "default": "git",
    },
    "checkout-persist-credentials": {
        "description": "Whether to configure the token or SSH key with local git config.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-path": {
        "description": "Relative path under GITHUB_WORKSPACE to place the repository.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-clean": {
        "description": "Whether to clean and reset before fetching.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-filter": {
        "description": "Partial clone filter. Overrides sparse checkout when set.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-sparse-checkout": {
        "description": "Sparse checkout patterns separated by new lines.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-sparse-checkout-cone-mode": {
        "description": "Whether to use cone mode for sparse checkout.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-fetch-depth": {
        "description": "Number of commits to fetch. Use 0 for all history.",
        "type": "number",
        "required": False,
        "default": 1,
    },
    "checkout-fetch-tags": {
        "description": "Whether to fetch tags when fetch-depth is greater than 0.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "checkout-show-progress": {
        "description": "Whether to show fetch progress output.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-lfs": {
        "description": "Whether to download Git LFS files.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "checkout-submodules": {
        "description": "Whether to checkout submodules; use recursive for nested submodules.",
        "type": "string",
        "required": False,
        "default": "false",
    },
    "checkout-set-safe-directory": {
        "description": "Whether to add the repository path as a safe Git directory.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-github-server-url": {
        "description": "GitHub server URL to fetch from.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-allow-unsafe-pr-checkout": {
        "description": "Allow checkout of fork pull request code in trusted contexts.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
}

CHECKOUT_SECRETS: dict[str, dict[str, Any]] = {
    "checkout-token": {
        "description": "Token used by actions/checkout. Defaults to github.token.",
        "required": False,
    },
    "checkout-ssh-key": {
        "description": "SSH key used by actions/checkout.",
        "required": False,
    },
}

ARTIFACT_DOWNLOAD_INPUTS: dict[str, dict[str, Any]] = {
    "artifact-download-enabled": {
        "description": "Whether to download artifacts before workflow execution.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-download-name": {
        "description": "Name of the artifact to download. Leave empty to download all artifacts.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-download-ids": {
        "description": (
            "Comma-separated artifact IDs to download. Mutually exclusive with "
            "artifact-download-name."
        ),
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-download-path": {
        "description": "Destination path for downloaded artifacts.",
        "type": "string",
        "required": False,
        "default": ".",
    },
    "artifact-download-pattern": {
        "description": "Glob pattern matching artifacts to download when name is unset.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-download-merge-multiple": {
        "description": "Whether multiple matched artifacts are extracted into one directory.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-download-repository": {
        "description": "Repository to download artifacts from when a token is set.",
        "type": "string",
        "required": False,
        "default": "${{ github.repository }}",
    },
    "artifact-download-run-id": {
        "description": "Workflow run ID to download artifacts from when a token is set.",
        "type": "string",
        "required": False,
        "default": "${{ github.run_id }}",
    },
    "artifact-download-skip-decompress": {
        "description": "Whether to download the artifact archive without extracting it.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-download-digest-mismatch": {
        "description": "Behavior when a downloaded artifact digest does not match.",
        "type": "string",
        "required": False,
        "default": "error",
    },
}

ARTIFACT_DOWNLOAD_SECRETS: dict[str, dict[str, Any]] = {
    "artifact-download-token": {
        "description": "Token used to download artifacts from another repository or run.",
        "required": False,
    },
}

ARTIFACT_UPLOAD_INPUTS: dict[str, dict[str, Any]] = {
    "artifact-upload-enabled": {
        "description": "Whether to upload artifacts after workflow execution.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-upload-path": {
        "description": "File, directory, or wildcard pattern to upload after workflow execution.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-upload-name": {
        "description": "Artifact name.",
        "type": "string",
        "required": False,
        "default": "artifact",
    },
    "artifact-upload-if-no-files-found": {
        "description": "Behavior when no files match artifact-upload-path.",
        "type": "string",
        "required": False,
        "default": "warn",
    },
    "artifact-upload-retention-days": {
        "description": "Artifact retention in days. Use 0 for repository default.",
        "type": "number",
        "required": False,
        "default": 0,
    },
    "artifact-upload-compression-level": {
        "description": "Compression level from 0 to 9.",
        "type": "number",
        "required": False,
        "default": 6,
    },
    "artifact-upload-overwrite": {
        "description": "Whether to overwrite an existing artifact with the same name.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-upload-include-hidden-files": {
        "description": "Whether hidden files under artifact-upload-path are included.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-upload-archive": {
        "description": "Whether upload-artifact archives files before upload.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
}

COMMIT_INPUTS: dict[str, dict[str, Any]] = {
    "commit-enabled": {
        "description": (
            "Whether to commit selected generated files back to a repository. The "
            "writeback commit runs in a nested job that statically requires "
            "contents: write (and actions: read), so any job calling this workflow "
            "must grant permissions: contents: write, actions: read even when this "
            "is false — GitHub validates the nested permissions before the run starts."
        ),
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "commit-paths": {
        "description": "Newline-separated files or directories to include in the writeback commit.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "commit-delete-paths": {
        "description": "Newline-separated files or directories to delete in the writeback commit.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "commit-message": {
        "description": "Commit message for generated file writeback.",
        "type": "string",
        "required": False,
        "default": "chore: update generated files",
    },
    "commit-repository": {
        "description": "Repository name with owner to commit to.",
        "type": "string",
        "required": False,
        "default": "${{ github.repository }}",
    },
    "commit-branch": {
        "description": "Branch to check out and push generated changes to.",
        "type": "string",
        "required": False,
        "default": "${{ github.ref_name }}",
    },
    "commit-author-name": {
        "description": "Git author name for generated file commits.",
        "type": "string",
        "required": False,
        "default": "github-actions[bot]",
    },
    "commit-author-email": {
        "description": "Git author email for generated file commits.",
        "type": "string",
        "required": False,
        "default": "41898282+github-actions[bot]@users.noreply.github.com",
    },
    "commit-push": {
        "description": "Whether to push the generated commit.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "commit-expected-base-sha": {
        "description": (
            "Optional SHA that the writeback target branch must point to before committing."
        ),
        "type": "string",
        "required": False,
        "default": "",
    },
    "commit-internal-artifact-name": {
        "description": (
            "Internal artifact name used to transfer the writeback payload. Defaults to a "
            "run-scoped name. Callers that invoke a commit-enabled workflow multiple times "
            "within one run must pass distinct values, because input defaults cannot "
            "disambiguate per invocation."
        ),
        "type": "string",
        "required": False,
        "default": "devflows-writeback",
    },
}

COMMIT_SECRETS: dict[str, dict[str, Any]] = {
    "commit-token": {
        "description": (
            "Token used by the writeback job. Must be able to write contents when "
            "commit-enabled is true."
        ),
        "required": False,
    },
}
