from __future__ import annotations

import re
from copy import deepcopy
from pathlib import Path, PurePosixPath
from typing import Any

from devflows.actions import annotate_pins
from devflows.actions import ref as action_ref
from devflows.catalog import CATALOG_DIR, Workflow
from devflows.errors import DevflowsError
from devflows.yaml import dump_yaml

# At sync time each workflow's runtime scripts are inlined into the generated
# YAML (rather than checked out from the DevFlows repo at run time, which broke
# cross-repo consumers because github.workflow_ref is the caller's ref). The
# materialize step writes each script to $RUNNER_TEMP/devflows/<path> via a
# single-quoted heredoc so the body is emitted verbatim with no shell expansion.
RUNTIME_SCRIPT_DELIMITER = "DEVFLOWS_SCRIPT_EOF"
RUNTIME_SCRIPT_ROOT = "$RUNNER_TEMP/devflows"
_SCRIPT_REF_PATTERN = re.compile(r"\$\{DEVFLOWS_SCRIPT_ROOT\}/([A-Za-z0-9_./-]+\.py)")

GENERATED_HEADER_TEMPLATE = "# GENERATED by devflows sync — do not edit; source: workflows/{id}/\n"


def render_published_workflow(item: Workflow) -> str:
    header = GENERATED_HEADER_TEMPLATE.format(id=item.id)
    if not _io_config(item):
        body = item.workflow_path.read_text(encoding="utf-8")
    else:
        body = dump_yaml(build_published_workflow(item))
    return header + annotate_pins(body)


def build_published_workflow(item: Workflow) -> dict[str, Any]:
    workflow = deepcopy(item.workflow)
    io_config = _io_config(item)
    if not io_config:
        return workflow

    workflow_call = _workflow_call(workflow)
    inputs = workflow_call.setdefault("inputs", {})
    secrets = workflow_call.setdefault("secrets", {})

    if _enabled(io_config, "checkout"):
        inputs.update(deepcopy(CHECKOUT_INPUTS))
        secrets.update(deepcopy(CHECKOUT_SECRETS))
    if _enabled(io_config, "artifact-download"):
        inputs.update(deepcopy(ARTIFACT_DOWNLOAD_INPUTS))
        secrets.update(deepcopy(ARTIFACT_DOWNLOAD_SECRETS))
    if _enabled(io_config, "artifact-upload"):
        inputs.update(deepcopy(ARTIFACT_UPLOAD_INPUTS))
    if _enabled(io_config, "writeback"):
        inputs.update(deepcopy(COMMIT_INPUTS))
        # Run-scope the default so two commit-enabled invocations of the same
        # workflow across different runs cannot clobber each other's payload
        # (the upload step uses overwrite: true). Reusable-workflow input
        # defaults may reference the github context. Multiple invocations within
        # a single run still need distinct caller-provided names (see description).
        inputs["commit-internal-artifact-name"]["default"] = (
            f"devflows-{item.id}-writeback-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}"
        )
        secrets.update(deepcopy(COMMIT_SECRETS))

    job_id = str(io_config.get("job") or _first_runner_job_id(workflow))
    jobs = workflow.setdefault("jobs", {})
    if job_id not in jobs:
        raise ValueError(f"{item.metadata_path}: io.job {job_id!r} does not exist.")
    job = jobs[job_id]
    if not isinstance(job, dict) or "steps" not in job:
        raise ValueError(f"{item.metadata_path}: io.job {job_id!r} must be a runner job.")

    prefix_steps: list[dict[str, Any]] = []
    suffix_steps: list[dict[str, Any]] = []
    if _enabled(io_config, "checkout"):
        prefix_steps.append(_checkout_step())
    if _enabled(io_config, "artifact-download"):
        prefix_steps.append(_download_artifact_step())
    if _enabled(io_config, "artifact-upload"):
        suffix_steps.append(_upload_artifact_step())
    if _enabled(io_config, "writeback"):
        suffix_steps.extend(_create_writeback_steps())
        jobs["commit"] = _commit_job(job_id)

    original_steps = list(job.get("steps", []))
    assembled = prefix_steps + original_steps + suffix_steps
    if _enabled(io_config, "runtime"):
        # Materialize after checkout/download (which never reference scripts) and
        # before the domain steps that invoke them.
        assembled.insert(len(prefix_steps), _materialize_step(item, assembled))
    job["steps"] = assembled

    for runtime_job_id in _runtime_job_ids(io_config):
        runtime_job = jobs.get(runtime_job_id)
        if not isinstance(runtime_job, dict) or "steps" not in runtime_job:
            raise ValueError(
                f"{item.metadata_path}: io.runtime-jobs item {runtime_job_id!r} "
                "must be a runner job."
            )
        runtime_steps = list(runtime_job.get("steps", []))
        runtime_job["steps"] = [_materialize_step(item, runtime_steps), *runtime_steps]
    workflow_permissions = workflow.get("permissions")
    _ensure_job_permissions(
        job,
        workflow_permissions if isinstance(workflow_permissions, dict) else {},
        contents="read",
        actions="read"
        if any(
            _enabled(io_config, channel)
            for channel in ("artifact-download", "artifact-upload", "writeback")
        )
        else None,
    )
    return workflow


def validate_publish_config(item: Workflow) -> list[str]:
    errors: list[str] = []
    config = _io_config(item)
    if not config:
        return errors
    supported = {
        "artifact-download",
        "artifact-upload",
        "checkout",
        "job",
        "runtime",
        "writeback",
        "runtime-jobs",
    }
    for key in config:
        if key not in supported:
            errors.append(f"{item.metadata_path}: io.{key} is not supported.")
    if _enabled(config, "writeback") and not _enabled(config, "runtime"):
        errors.append(f"{item.metadata_path}: io.writeback requires io.runtime.")
    job_id = str(config.get("job") or "")
    jobs = item.workflow.get("jobs") or {}
    if job_id:
        job = jobs.get(job_id)
        if not isinstance(job, dict) or "steps" not in job:
            errors.append(f"{item.metadata_path}: io.job {job_id!r} must be a runner job.")
    elif not any(isinstance(job, dict) and "steps" in job for job in jobs.values()):
        errors.append(f"{item.metadata_path}: io requires at least one runner job.")
    runtime_jobs = config.get("runtime-jobs", []) or []
    if not isinstance(runtime_jobs, list):
        errors.append(f"{item.metadata_path}: io.runtime-jobs must be a list.")
    else:
        for runtime_job_id in runtime_jobs:
            job = jobs.get(str(runtime_job_id))
            if not isinstance(job, dict) or "steps" not in job:
                errors.append(
                    f"{item.metadata_path}: io.runtime-jobs item {runtime_job_id!r} "
                    "must be a runner job."
                )
    return errors


def published_workflow_call(item: Workflow) -> dict[str, Any]:
    workflow_call = _workflow_call(build_published_workflow(item))
    return workflow_call if isinstance(workflow_call, dict) else {}


def write_published_workflow(path: Path, item: Workflow) -> None:
    path.write_text(render_published_workflow(item).rstrip() + "\n", encoding="utf-8")


def _workflow_call(workflow: dict[str, Any]) -> dict[str, Any]:
    on_block = workflow.setdefault("on", {})
    if not isinstance(on_block, dict):
        raise ValueError("workflow on block must be a mapping.")
    workflow_call = on_block.setdefault("workflow_call", {})
    if not isinstance(workflow_call, dict):
        raise ValueError("workflow_call block must be a mapping.")
    return workflow_call


def _io_config(item: Workflow) -> dict[str, Any]:
    config = item.metadata.get("io") or {}
    if config is True:
        return {"checkout": True, "artifact-download": True, "artifact-upload": True}
    if not isinstance(config, dict):
        return {}
    return config


def _enabled(config: dict[str, Any], name: str) -> bool:
    return bool(config.get(name))


def _runtime_job_ids(config: dict[str, Any]) -> list[str]:
    return [str(item) for item in config.get("runtime-jobs", []) or []]


def _first_runner_job_id(workflow: dict[str, Any]) -> str:
    jobs = workflow.get("jobs") or {}
    for job_id, job in jobs.items():
        if isinstance(job, dict) and "steps" in job:
            return str(job_id)
    raise ValueError("workflow must contain at least one runner job for IO injection.")


def _ensure_job_permissions(
    job: dict[str, Any],
    workflow_permissions: dict[str, Any],
    **permissions: str | None,
) -> None:
    current = job.setdefault("permissions", {})
    if current is None:
        current = {}
        job["permissions"] = current
    if not isinstance(current, dict):
        return
    for name, level in permissions.items():
        if level is None:
            continue
        if str(workflow_permissions.get(name) or "") == level:
            continue
        if name not in current:
            current[name] = level
    if not current:
        job.pop("permissions", None)


def _checkout_step() -> dict[str, Any]:
    return {
        "name": "Checkout repository",
        "if": "inputs.checkout-enabled",
        "uses": action_ref("checkout"),
        "with": {
            "repository": "${{ inputs.checkout-repository }}",
            "ref": "${{ inputs.checkout-ref }}",
            "token": "${{ secrets.checkout-token || github.token }}",
            "ssh-key": "${{ secrets.checkout-ssh-key }}",
            "ssh-known-hosts": "${{ inputs.checkout-ssh-known-hosts }}",
            "ssh-strict": "${{ inputs.checkout-ssh-strict }}",
            "ssh-user": "${{ inputs.checkout-ssh-user }}",
            "persist-credentials": "${{ inputs.checkout-persist-credentials }}",
            "path": "${{ inputs.checkout-path }}",
            "clean": "${{ inputs.checkout-clean }}",
            "filter": "${{ inputs.checkout-filter }}",
            "sparse-checkout": "${{ inputs.checkout-sparse-checkout }}",
            "sparse-checkout-cone-mode": "${{ inputs.checkout-sparse-checkout-cone-mode }}",
            "fetch-depth": "${{ inputs.checkout-fetch-depth }}",
            "fetch-tags": "${{ inputs.checkout-fetch-tags }}",
            "show-progress": "${{ inputs.checkout-show-progress }}",
            "lfs": "${{ inputs.checkout-lfs }}",
            "submodules": "${{ inputs.checkout-submodules }}",
            "set-safe-directory": "${{ inputs.checkout-set-safe-directory }}",
            "github-server-url": "${{ inputs.checkout-github-server-url }}",
            "allow-unsafe-pr-checkout": "${{ inputs.checkout-allow-unsafe-pr-checkout }}",
        },
    }


def _download_artifact_step() -> dict[str, Any]:
    return {
        "name": "Download artifacts",
        "if": "inputs.artifact-download-enabled",
        "uses": action_ref("download-artifact"),
        "with": {
            "name": "${{ inputs.artifact-download-name }}",
            "artifact-ids": "${{ inputs.artifact-download-ids }}",
            "path": "${{ inputs.artifact-download-path }}",
            "pattern": "${{ inputs.artifact-download-pattern }}",
            "merge-multiple": "${{ inputs.artifact-download-merge-multiple }}",
            "github-token": "${{ secrets.artifact-download-token }}",
            "repository": "${{ inputs.artifact-download-repository }}",
            "run-id": "${{ inputs.artifact-download-run-id }}",
            "skip-decompress": "${{ inputs.artifact-download-skip-decompress }}",
            "digest-mismatch": "${{ inputs.artifact-download-digest-mismatch }}",
        },
    }


def _referenced_scripts(steps: list[dict[str, Any]]) -> list[str]:
    """Relative script paths referenced via ${DEVFLOWS_SCRIPT_ROOT}/... in run blocks."""
    seen: list[str] = []
    for step in steps:
        run = step.get("run")
        if not isinstance(run, str):
            continue
        for match in _SCRIPT_REF_PATTERN.finditer(run):
            relpath = match.group(1)
            if relpath not in seen:
                seen.append(relpath)
    return seen


def _source_script_path(item: Workflow, relpath: str) -> Path:
    """Map a published script reference (e.g. `pandoc/run-pandoc.py`) to its source."""
    workflow_id, _, rest = relpath.partition("/")
    if not rest:
        raise DevflowsError(
            f"{item.metadata_path}: runtime script reference {relpath!r} must be "
            "of the form <workflow-id>/<script>."
        )
    source = CATALOG_DIR / workflow_id / "scripts" / rest
    if not source.is_file():
        raise DevflowsError(
            f"{item.metadata_path}: runtime script {relpath!r} not found at {source}."
        )
    return source


def _materialize_step(item: Workflow, steps: list[dict[str, Any]]) -> dict[str, Any]:
    """Build a step that writes referenced scripts to $RUNNER_TEMP/devflows/<path>."""
    lines = ["set -euo pipefail"]
    for relpath in _referenced_scripts(steps):
        source = _source_script_path(item, relpath)
        content = source.read_text(encoding="utf-8")
        if RUNTIME_SCRIPT_DELIMITER in content:
            raise DevflowsError(
                f"{source}: script contains the heredoc delimiter "
                f"{RUNTIME_SCRIPT_DELIMITER!r}, so it cannot be inlined safely."
            )
        target = f"{RUNTIME_SCRIPT_ROOT}/{relpath}"
        directory = PurePosixPath(target).parent.as_posix()
        lines.append(f'mkdir -p "{directory}"')
        lines.append(f"cat > \"{target}\" <<'{RUNTIME_SCRIPT_DELIMITER}'")
        lines.append(content.rstrip("\n"))
        lines.append(RUNTIME_SCRIPT_DELIMITER)
    lines.append(f'echo "script-root={RUNTIME_SCRIPT_ROOT}" >> "$GITHUB_OUTPUT"')
    return {
        "name": "Materialize DevFlows runtime scripts",
        "id": "devflows-runtime",
        "shell": "bash",
        "run": "\n".join(lines),
    }


def _upload_artifact_step() -> dict[str, Any]:
    return {
        "name": "Upload artifact",
        "if": "inputs.artifact-upload-enabled && inputs.artifact-upload-path != ''",
        "uses": action_ref("upload-artifact"),
        "with": {
            "name": "${{ inputs.artifact-upload-name }}",
            "path": "${{ inputs.artifact-upload-path }}",
            "if-no-files-found": "${{ inputs.artifact-upload-if-no-files-found }}",
            "retention-days": "${{ inputs.artifact-upload-retention-days }}",
            "compression-level": "${{ inputs.artifact-upload-compression-level }}",
            "overwrite": "${{ inputs.artifact-upload-overwrite }}",
            "include-hidden-files": "${{ inputs.artifact-upload-include-hidden-files }}",
            "archive": "${{ inputs.artifact-upload-archive }}",
        },
    }


def _create_writeback_steps() -> list[dict[str, Any]]:
    return [
        {
            "name": "Create writeback payload",
            "if": "inputs.commit-enabled",
            "env": {
                "DEVFLOWS_SCRIPT_ROOT": "${{ steps.devflows-runtime.outputs.script-root }}",
                "WRITEBACK_DELETE_PATHS": "${{ inputs.commit-delete-paths }}",
                "WRITEBACK_PATHS": "${{ inputs.commit-paths }}",
                "WRITEBACK_PAYLOAD_DIR": ".devflows-writeback/payload",
                "WRITEBACK_SOURCE_REF": "${{ github.ref }}",
                "WRITEBACK_SOURCE_REPOSITORY": "${{ github.repository }}",
                "WRITEBACK_SOURCE_SHA": "${{ github.sha }}",
            },
            "shell": "bash",
            "run": 'python "${DEVFLOWS_SCRIPT_ROOT}/writeback/create-payload.py"',
        },
        {
            "name": "Upload writeback payload",
            "if": "inputs.commit-enabled",
            "uses": action_ref("upload-artifact"),
            "with": {
                "name": "${{ inputs.commit-internal-artifact-name }}",
                "path": ".devflows-writeback/payload",
                "if-no-files-found": "error",
                "retention-days": 1,
                "compression-level": 0,
                "overwrite": True,
                "include-hidden-files": True,
            },
        },
    ]


def _commit_job(needs: str) -> dict[str, Any]:
    # This nested reusable-workflow call uses a relative ref. Per GitHub's
    # documentation ("Reuse workflows"): a workflow called without {owner}/{repo}
    # and @{ref} "is from the same commit as the caller workflow" — here the caller
    # is the file containing this uses (e.g. pandoc.yaml), not the top-level
    # consumer. So when a consumer calls pandoc.yaml@<devflows-sha> cross-repo, this
    # resolves to writeback.yaml at that same devflows repo+SHA, caller-independent.
    # (This differs from composite-action `./` refs, which resolve against the
    # caller's checked-out workspace; secondary sources sometimes conflate the two.)
    # Verified against docs.github.com/actions/.../reuse-workflows, 2026-07.
    return {
        "name": "Commit generated files",
        "needs": needs,
        "if": "inputs.commit-enabled",
        "uses": "./.github/workflows/writeback.yaml",
        "permissions": {"actions": "read", "contents": "write"},
        "with": {
            "writeback-artifact-name": "${{ inputs.commit-internal-artifact-name }}",
            "commit-repository": "${{ inputs.commit-repository }}",
            "commit-branch": "${{ inputs.commit-branch }}",
            "commit-message": "${{ inputs.commit-message }}",
            "commit-author-name": "${{ inputs.commit-author-name }}",
            "commit-author-email": "${{ inputs.commit-author-email }}",
            "commit-push": "${{ inputs.commit-push }}",
            "commit-expected-base-sha": "${{ inputs.commit-expected-base-sha }}",
        },
        "secrets": {"commit-token": "${{ secrets.commit-token }}"},
    }


CHECKOUT_INPUTS: dict[str, dict[str, Any]] = {
    "checkout-enabled": {
        "description": "Whether to run actions/checkout before workflow execution.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-repository": {
        "description": "Repository name with owner to checkout.",
        "type": "string",
        "required": False,
        "default": "${{ github.repository }}",
    },
    "checkout-ref": {
        "description": "Branch, tag, or SHA to checkout.",
        "type": "string",
        "required": False,
        "default": "${{ github.ref }}",
    },
    "checkout-ssh-known-hosts": {
        "description": "Known hosts in addition to the user and global host key database.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-ssh-strict": {
        "description": "Whether to perform strict host key checking.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-ssh-user": {
        "description": "SSH user to use when connecting to the remote SSH host.",
        "type": "string",
        "required": False,
        "default": "git",
    },
    "checkout-persist-credentials": {
        "description": "Whether to configure the token or SSH key with local git config.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-path": {
        "description": "Relative path under GITHUB_WORKSPACE to place the repository.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-clean": {
        "description": "Whether to clean and reset before fetching.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-filter": {
        "description": "Partial clone filter. Overrides sparse checkout when set.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-sparse-checkout": {
        "description": "Sparse checkout patterns separated by new lines.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-sparse-checkout-cone-mode": {
        "description": "Whether to use cone mode for sparse checkout.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-fetch-depth": {
        "description": "Number of commits to fetch. Use 0 for all history.",
        "type": "number",
        "required": False,
        "default": 1,
    },
    "checkout-fetch-tags": {
        "description": "Whether to fetch tags when fetch-depth is greater than 0.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "checkout-show-progress": {
        "description": "Whether to show fetch progress output.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-lfs": {
        "description": "Whether to download Git LFS files.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "checkout-submodules": {
        "description": "Whether to checkout submodules; use recursive for nested submodules.",
        "type": "string",
        "required": False,
        "default": "false",
    },
    "checkout-set-safe-directory": {
        "description": "Whether to add the repository path as a safe Git directory.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "checkout-github-server-url": {
        "description": "GitHub server URL to fetch from.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "checkout-allow-unsafe-pr-checkout": {
        "description": "Allow checkout of fork pull request code in trusted contexts.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
}

CHECKOUT_SECRETS: dict[str, dict[str, Any]] = {
    "checkout-token": {
        "description": "Token used by actions/checkout. Defaults to github.token.",
        "required": False,
    },
    "checkout-ssh-key": {
        "description": "SSH key used by actions/checkout.",
        "required": False,
    },
}

ARTIFACT_DOWNLOAD_INPUTS: dict[str, dict[str, Any]] = {
    "artifact-download-enabled": {
        "description": "Whether to download artifacts before workflow execution.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-download-name": {
        "description": "Name of the artifact to download. Leave empty to download all artifacts.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-download-ids": {
        "description": (
            "Comma-separated artifact IDs to download. Mutually exclusive with "
            "artifact-download-name."
        ),
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-download-path": {
        "description": "Destination path for downloaded artifacts.",
        "type": "string",
        "required": False,
        "default": ".",
    },
    "artifact-download-pattern": {
        "description": "Glob pattern matching artifacts to download when name is unset.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-download-merge-multiple": {
        "description": "Whether multiple matched artifacts are extracted into one directory.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-download-repository": {
        "description": "Repository to download artifacts from when a token is set.",
        "type": "string",
        "required": False,
        "default": "${{ github.repository }}",
    },
    "artifact-download-run-id": {
        "description": "Workflow run ID to download artifacts from when a token is set.",
        "type": "string",
        "required": False,
        "default": "${{ github.run_id }}",
    },
    "artifact-download-skip-decompress": {
        "description": "Whether to download the artifact archive without extracting it.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-download-digest-mismatch": {
        "description": "Behavior when a downloaded artifact digest does not match.",
        "type": "string",
        "required": False,
        "default": "error",
    },
}

ARTIFACT_DOWNLOAD_SECRETS: dict[str, dict[str, Any]] = {
    "artifact-download-token": {
        "description": "Token used to download artifacts from another repository or run.",
        "required": False,
    },
}

ARTIFACT_UPLOAD_INPUTS: dict[str, dict[str, Any]] = {
    "artifact-upload-enabled": {
        "description": "Whether to upload artifacts after workflow execution.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-upload-path": {
        "description": "File, directory, or wildcard pattern to upload after workflow execution.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "artifact-upload-name": {
        "description": "Artifact name.",
        "type": "string",
        "required": False,
        "default": "artifact",
    },
    "artifact-upload-if-no-files-found": {
        "description": "Behavior when no files match artifact-upload-path.",
        "type": "string",
        "required": False,
        "default": "warn",
    },
    "artifact-upload-retention-days": {
        "description": "Artifact retention in days. Use 0 for repository default.",
        "type": "number",
        "required": False,
        "default": 0,
    },
    "artifact-upload-compression-level": {
        "description": "Compression level from 0 to 9.",
        "type": "number",
        "required": False,
        "default": 6,
    },
    "artifact-upload-overwrite": {
        "description": "Whether to overwrite an existing artifact with the same name.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-upload-include-hidden-files": {
        "description": "Whether hidden files under artifact-upload-path are included.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "artifact-upload-archive": {
        "description": "Whether upload-artifact archives files before upload.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
}

COMMIT_INPUTS: dict[str, dict[str, Any]] = {
    "commit-enabled": {
        "description": "Whether to commit selected generated files back to a repository.",
        "type": "boolean",
        "required": False,
        "default": False,
    },
    "commit-paths": {
        "description": "Newline-separated files or directories to include in the writeback commit.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "commit-delete-paths": {
        "description": "Newline-separated files or directories to delete in the writeback commit.",
        "type": "string",
        "required": False,
        "default": "",
    },
    "commit-message": {
        "description": "Commit message for generated file writeback.",
        "type": "string",
        "required": False,
        "default": "chore: update generated files",
    },
    "commit-repository": {
        "description": "Repository name with owner to commit to.",
        "type": "string",
        "required": False,
        "default": "${{ github.repository }}",
    },
    "commit-branch": {
        "description": "Branch to check out and push generated changes to.",
        "type": "string",
        "required": False,
        "default": "${{ github.ref_name }}",
    },
    "commit-author-name": {
        "description": "Git author name for generated file commits.",
        "type": "string",
        "required": False,
        "default": "github-actions[bot]",
    },
    "commit-author-email": {
        "description": "Git author email for generated file commits.",
        "type": "string",
        "required": False,
        "default": "41898282+github-actions[bot]@users.noreply.github.com",
    },
    "commit-push": {
        "description": "Whether to push the generated commit.",
        "type": "boolean",
        "required": False,
        "default": True,
    },
    "commit-expected-base-sha": {
        "description": (
            "Optional SHA that the writeback target branch must point to before committing."
        ),
        "type": "string",
        "required": False,
        "default": "",
    },
    "commit-internal-artifact-name": {
        "description": (
            "Internal artifact name used to transfer the writeback payload. Defaults to a "
            "run-scoped name. Callers that invoke a commit-enabled workflow multiple times "
            "within one run must pass distinct values, because input defaults cannot "
            "disambiguate per invocation."
        ),
        "type": "string",
        "required": False,
        "default": "devflows-writeback",
    },
}

COMMIT_SECRETS: dict[str, dict[str, Any]] = {
    "commit-token": {
        "description": (
            "Token used by the writeback job. Must be able to write contents when "
            "commit-enabled is true."
        ),
        "required": False,
    },
}
