from __future__ import annotations

import json
import re
import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from devflows.actions import ref as action_ref
from devflows.catalog import PUBLISHED_DIR, Workflow
from devflows.publish import (
    assert_within_size_cap,
    build_published_workflow,
    caller_required_permissions,
    published_workflow_call,
)
from devflows.yaml import dump_yaml

# One hosted and one local scenario workflow are generated PER catalog workflow
# that owns scenarios, rather than a single monolithic file. GitHub startup-rejects
# an oversized workflow file (an opaque "workflow file issue" with zero jobs), and
# with every workflow's scenarios concatenated the hosted file crossed that ceiling.
# Partitioning by owning workflow keeps each file small; GitHub runs the separate
# files in parallel on the same event, so total scenario coverage is unchanged.
SCENARIOS_DIR = PUBLISHED_DIR
# Filename globs the scenario generator owns under .github/workflows/. Any file
# matching these but absent from a fresh generation -- the retired monolithic
# devflows-scenarios.yaml / devflows-local-scenarios.yaml, or a per-workflow file
# whose owning workflow no longer has scenarios for that runner -- is pruned so
# `devflows sync` / `devflows test-generate` leave a clean tree.
_SCENARIO_FILE_GLOBS = ("devflows-scenarios*.yaml", "devflows-local-scenarios*.yaml")


def hosted_scenario_path(workflow_id: str) -> Path:
    """Generated hosted scenario workflow for one catalog workflow."""
    return SCENARIOS_DIR / f"devflows-scenarios-{workflow_id}.yaml"


def local_scenario_path(workflow_id: str) -> Path:
    """Generated local (act) scenario workflow for one catalog workflow."""
    return SCENARIOS_DIR / f"devflows-scenarios-{workflow_id}.local.yaml"


# Harness scripts are real, lint-and-test-covered .py files. The generated
# workflows check the repository out and invoke them from this committed
# directory (they are no longer emitted as generated copies under
# .github/workflows/), so there is a single source of truth for each script.
HARNESS_SCRIPT_DIR = Path("harness/scenarios")
LOCAL_EVENT_PATH = Path(".act/push.json")
# SHA pins come from the central registry (devflows.actions) so they stay in
# lockstep with the pins the publisher injects.
DOWNLOAD_ARTIFACT_REF = action_ref("download-artifact")
UPLOAD_ARTIFACT_REF = action_ref("upload-artifact")
CHECKOUT_REF = action_ref("checkout")
ACT_PLATFORM = "ubuntu-latest=catthehacker/ubuntu:act-latest"
SCENARIO_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*$")
# A job guarded by this expression runs on same-repo pull requests, pushes, and
# manual dispatches, but is skipped on fork pull requests. GitHub caps a fork
# PR's token to read, so a call job that declares any write permission would fail
# the nested-permission superset check at startup; skipping it keeps the whole
# workflow startable for external contributors while same-repo PRs run fully.
_FORK_SAFE_IF = (
    "github.event_name != 'pull_request' "
    "|| github.event.pull_request.head.repo.full_name == github.repository"
)
_HOSTED_HEADER = (
    "# GENERATED by devflows test-generate — do not edit; source: workflows/*/devflow.yaml.\n"
    "# Scenarios whose reusable-workflow call needs a write permission are gated with a\n"
    "# fork-safe `if:` (and so are the jobs that depend on them): fork pull requests skip\n"
    "# them because GitHub caps the fork token to read and would fail the nested-permission\n"
    "# check at startup. Same-repo pull requests, pushes to main, and workflow_dispatch\n"
    "# still run every scenario.\n"
)
_LOCAL_HEADER = (
    "# GENERATED by devflows test-generate — do not edit; source: workflows/*/devflow.yaml.\n"
    "# This workflow only works under `act`. Run it with `task scenarios-local`; the\n"
    "# require-act guard job fails fast if it is dispatched on GitHub-hosted runners.\n"
)
# Inputs the ephemeral-branch mutation harness drives on the call job. Any
# workflow that exposes all of them is expressible as a mutation target, which
# generalizes the harness beyond the writeback workflow.
MUTATION_REQUIRED_INPUTS = (
    "commit-branch",
    "commit-expected-base-sha",
    "commit-repository",
    "writeback-artifact-name",
)


def _script(name: str) -> str:
    return (HARNESS_SCRIPT_DIR / name).as_posix()


def _required_call_permissions(workflow: Workflow) -> dict[str, str]:
    """Permissions a caller must grant to invoke ``workflow`` as a reusable call.

    GitHub caps (never elevates) the GITHUB_TOKEN through a reusable-workflow
    chain, and a nested call that declares more than the caller granted fails the
    run at startup (the pandoc ``commit`` job that requests ``contents: write`` is
    the canonical case). Granting the union of every permission the published
    workflow declares (top level plus each job) guarantees the caller is a
    superset, so no call startup-fails and writeback jobs can push at runtime.
    """
    return caller_required_permissions(build_published_workflow(workflow))


def _missing_mutation_inputs(workflow: Workflow) -> list[str]:
    """Mutation-harness inputs the target workflow does not expose (empty = OK)."""
    call_inputs = set(published_workflow_call(workflow).get("inputs") or {})
    return [name for name in MUTATION_REQUIRED_INPUTS if name not in call_inputs]


# --- validation-failure scenario support -----------------------------------
#
# A validation-failure scenario does NOT call the reusable workflow. Instead the
# generated job checks the repo out and runs the target workflow's
# `validate-inputs.py` directly, with the env the workflow's own validate step
# would set, so the *input-validation script layer* is exercised honestly in CI.
# (A full reusable-call failure e2e is a future sandbox-repo capability.)

VALIDATE_SCRIPT_NAME = "validate-inputs.py"
# The runtime script-root the published workflow uses to LOCATE the validate
# script (steps.devflows-runtime.outputs.script-root, materialized by the
# injected io.runtime step). The harness invokes the script by its checkout path
# instead, so an env entry bound to this expression is dropped, not reconstructed.
_RUNTIME_SCRIPT_ROOT_EXPR = "steps.devflows-runtime.outputs.script-root"
# Matches a ${{ ... }} expression and captures its inner text.
_EXPRESSION = re.compile(r"\$\{\{\s*(?P<expr>.+?)\s*\}\}")
# A bare reusable-workflow input reference, e.g. `inputs.docker-login-enabled`.
_INPUT_REF = re.compile(r"^inputs\.(?P<name>[A-Za-z0-9][A-Za-z0-9_-]*)$")


def _validate_step_run(workflow: Workflow) -> str:
    """The `run` string a discoverable validate step must invoke for ``workflow``."""
    return f"{workflow.id}/{VALIDATE_SCRIPT_NAME}"


def _find_validate_step(workflow: Workflow) -> dict[str, Any] | None:
    """Locate the source validate step, or None if the workflow has no such step.

    Discovery matches the step whose ``run`` invokes
    ``${DEVFLOWS_SCRIPT_ROOT}/<id>/validate-inputs.py`` (preferring a job keyed
    ``validate``), which is the promotion-time contract for input validation.
    """
    needle = _validate_step_run(workflow)
    jobs = workflow.workflow.get("jobs")
    if not isinstance(jobs, dict):
        return None

    def _step_from(job: Any) -> dict[str, Any] | None:
        if not isinstance(job, dict):
            return None
        for step in job.get("steps") or []:
            if isinstance(step, dict) and needle in str(step.get("run") or ""):
                return step
        return None

    # Prefer the conventional `validate` job, then fall back to any job.
    ordered = list(jobs.items())
    ordered.sort(key=lambda item: item[0] != "validate")
    for _job_id, job in ordered:
        step = _step_from(job)
        if step is not None:
            return step
    return None


def _serialize_input_value(value: Any) -> str:
    """Render an input value the way GitHub presents it to a ${{ inputs.x }} ref.

    GitHub hands booleans to expressions as the strings ``true``/``false`` and
    numbers as their canonical decimal string; strings pass through. The
    generated env values are plain strings, so the dumper quotes ``'true'`` /
    ``'3'`` to keep them from reloading as bool/int — consistent with how the
    call-job ``with:`` block feeds the same typed inputs to GitHub.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return ""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _workflow_input_defaults(workflow: Workflow) -> dict[str, Any]:
    """Declared defaults for each ``on.workflow_call`` input (missing => absent)."""
    inputs = workflow.workflow_call.get("inputs")
    if not isinstance(inputs, dict):
        return {}
    return {
        name: spec.get("default")
        for name, spec in inputs.items()
        if isinstance(spec, dict) and "default" in spec
    }


def _validate_env_errors(scenario: Scenario, step: dict[str, Any]) -> list[str]:
    """Reasons the validate step's env cannot be reconstructed from inputs alone."""
    errors: list[str] = []
    env = step.get("env")
    if env is not None and not isinstance(env, dict):
        return ["validate step env must be a mapping."]
    for key, raw in (env or {}).items():
        value = str(raw)
        if value.strip() == f"${{{{ {_RUNTIME_SCRIPT_ROOT_EXPR} }}}}":
            continue  # DevFlows runtime script-root; supplied by checkout path.
        for match in _EXPRESSION.finditer(value):
            expr = match.group("expr")
            if not _INPUT_REF.match(expr):
                errors.append(
                    f"validate step env {key!r} references {expr!r}; validation-failure "
                    "scenarios can only reconstruct inputs.<name> expressions "
                    "(github.*, steps.*, secrets.*, matrix.*, needs.* and compound "
                    "expressions are unsupported so substitution stays total)."
                )
    return errors


def _validation_failure_env(scenario: Scenario) -> dict[str, str]:
    """Reconstruct the validate step's env from the scenario inputs and defaults.

    Caller must have confirmed the step is discoverable and inputs-only via
    ``_find_validate_step``/``_validate_env_errors``.
    """
    step = _find_validate_step(scenario.workflow) or {}
    defaults = _workflow_input_defaults(scenario.workflow)
    env: dict[str, str] = {}
    for key, raw in (step.get("env") or {}).items():
        value = str(raw)
        if value.strip() == f"${{{{ {_RUNTIME_SCRIPT_ROOT_EXPR} }}}}":
            continue

        def _replace(match: re.Match[str]) -> str:
            ref = _INPUT_REF.match(match.group("expr"))
            # Guaranteed by _validate_env_errors, which runs before generation.
            assert ref is not None, match.group("expr")
            name = ref.group("name")
            resolved = scenario.inputs[name] if name in scenario.inputs else defaults.get(name)
            return _serialize_input_value(resolved)

        env[key] = _EXPRESSION.sub(_replace, value)
    return env


@dataclass(frozen=True)
class Scenario:
    workflow: Workflow
    id: str
    name: str
    runs: tuple[str, ...]
    inputs: dict[str, Any]
    assertions: tuple[dict[str, Any], ...]
    cleanup: tuple[str, ...]
    artifact: dict[str, Any]
    setup_artifact: dict[str, Any]
    mutation: dict[str, Any]
    writeback_payload: dict[str, Any]
    expect: str
    failure_message_contains: str

    @property
    def job_prefix(self) -> str:
        return f"{self.workflow.id}-{self.id}".replace("-", "_")

    @property
    def is_validation_failure(self) -> bool:
        return self.expect == "validation-failure"


def load_scenarios(workflows: list[Workflow]) -> list[Scenario]:
    scenarios: list[Scenario] = []
    for workflow in workflows:
        for raw_scenario in workflow.metadata.get("tests", {}).get("scenarios", []) or []:
            if not isinstance(raw_scenario, dict):
                continue
            scenarios.append(
                Scenario(
                    workflow=workflow,
                    id=str(raw_scenario.get("id") or ""),
                    name=str(raw_scenario.get("name") or raw_scenario.get("id") or ""),
                    runs=tuple(str(item) for item in raw_scenario.get("runs", []) or []),
                    inputs=dict(raw_scenario.get("inputs") or {}),
                    assertions=tuple(
                        dict(assertion) for assertion in raw_scenario.get("assertions", []) or []
                    ),
                    cleanup=tuple(str(path) for path in raw_scenario.get("cleanup", []) or []),
                    artifact=dict(raw_scenario.get("artifact") or {}),
                    setup_artifact=dict(raw_scenario.get("setup-artifact") or {}),
                    mutation=dict(raw_scenario.get("mutation") or {}),
                    writeback_payload=dict(raw_scenario.get("writeback-payload") or {}),
                    expect=str(raw_scenario.get("expect") or "success"),
                    failure_message_contains=str(
                        raw_scenario.get("failure-message-contains") or ""
                    ),
                )
            )
    return scenarios


def validate_scenarios(workflows: list[Workflow]) -> list[str]:
    errors: list[str] = []
    # Guard against duplicate generated job prefixes. Scenario ids feed the job
    # keys ({prefix}_call, {prefix}_assert, ...); a collision would silently
    # overwrite the earlier scenario's jobs, so it is a hard validation error.
    seen_prefixes: dict[str, Scenario] = {}
    # Branch prefixes must be unique across mutation scenarios: two scenarios
    # sharing one prefix could push/delete each other's ephemeral branches within
    # a run (cleanup globs {prefix}-{run_id}-*), corrupting both.
    seen_branch_prefixes: dict[str, Scenario] = {}
    for scenario in load_scenarios(workflows):
        prefix = f"{scenario.workflow.metadata_path}: tests.scenarios[{scenario.id or '?'}]"
        if not SCENARIO_ID_PATTERN.match(scenario.id):
            errors.append(f"{prefix}: id must match {SCENARIO_ID_PATTERN.pattern}.")
        previous = seen_prefixes.get(scenario.job_prefix)
        if previous is not None:
            errors.append(
                f"{prefix}: duplicate scenario id produces job prefix "
                f"{scenario.job_prefix!r}, already used by {previous.workflow.id} "
                f"scenario {previous.id!r}; scenario ids must be unique per workflow."
            )
        else:
            seen_prefixes[scenario.job_prefix] = scenario
        if not scenario.runs:
            errors.append(f"{prefix}: runs must include local, hosted, or both.")
        for runner in scenario.runs:
            if runner not in {"local", "hosted"}:
                errors.append(f"{prefix}: unsupported runner {runner!r}.")
        if not isinstance(scenario.inputs, dict):
            errors.append(f"{prefix}: inputs must be a mapping.")
        if scenario.expect not in {"success", "validation-failure"}:
            errors.append(f"{prefix}: expect must be 'success' or 'validation-failure'.")
        if scenario.failure_message_contains and not scenario.is_validation_failure:
            errors.append(
                f"{prefix}: failure-message-contains is only valid with expect: validation-failure."
            )
        if scenario.is_validation_failure:
            # This scenario runs the target workflow's validate-inputs.py directly
            # (no reusable-workflow call), so it must NOT carry any of the machinery
            # that only makes sense for a real call.
            for field_name, present in (
                ("assertions", bool(scenario.assertions)),
                ("artifact", bool(scenario.artifact)),
                ("setup-artifact", bool(scenario.setup_artifact)),
                ("mutation", bool(scenario.mutation)),
                ("writeback-payload", bool(scenario.writeback_payload)),
                ("cleanup", bool(scenario.cleanup)),
            ):
                if present:
                    errors.append(
                        f"{prefix}: validation-failure scenarios test the validate script "
                        f"only and cannot declare {field_name}."
                    )
            # The target must expose a discoverable validate step whose env can be
            # rebuilt from inputs alone (else substitution would be incomplete).
            step = _find_validate_step(scenario.workflow)
            if step is None:
                errors.append(
                    f"{prefix}: expect: validation-failure requires {scenario.workflow.id} to "
                    f"have a validate step running ${{DEVFLOWS_SCRIPT_ROOT}}/"
                    f"{scenario.workflow.id}/{VALIDATE_SCRIPT_NAME}; none was found."
                )
            else:
                errors.extend(
                    f"{prefix}: {message}" for message in _validate_env_errors(scenario, step)
                )
        if not scenario.assertions and not scenario.is_validation_failure:
            errors.append(f"{prefix}: assertions must not be empty.")
        if not scenario.mutation:
            for assertion in scenario.assertions:
                assertion_type = assertion.get("type")
                if assertion_type not in {
                    "file-exists",
                    "file-glob-exists",
                    "file-contains",
                    "workflow-output-equals",
                }:
                    errors.append(f"{prefix}: unsupported assertion type {assertion_type!r}.")
                if assertion_type in {
                    "file-exists",
                    "file-glob-exists",
                    "file-contains",
                } and not assertion.get("path"):
                    errors.append(f"{prefix}: {assertion_type} assertions require path.")
                if assertion_type == "file-contains" and "text" not in assertion:
                    errors.append(f"{prefix}: file-contains assertions require text.")
                if assertion_type == "workflow-output-equals":
                    if not assertion.get("name"):
                        errors.append(f"{prefix}: workflow-output-equals assertions require name.")
                    if "value" not in assertion:
                        errors.append(f"{prefix}: workflow-output-equals assertions require value.")
        if "hosted" in scenario.runs and _has_file_assertions(scenario) and not scenario.artifact:
            errors.append(f"{prefix}: hosted file assertions require artifact metadata.")
        if scenario.artifact and not scenario.artifact.get("name"):
            errors.append(f"{prefix}: artifact metadata requires name.")
        if scenario.setup_artifact:
            if "hosted" not in scenario.runs:
                errors.append(f"{prefix}: setup-artifact is supported for hosted scenarios.")
            if not scenario.setup_artifact.get("name"):
                errors.append(f"{prefix}: setup-artifact requires name.")
            if not scenario.setup_artifact.get("path"):
                errors.append(f"{prefix}: setup-artifact requires path.")
            files = scenario.setup_artifact.get("files")
            if not isinstance(files, list) or not files:
                errors.append(f"{prefix}: setup-artifact requires a nonempty files list.")
            else:
                for index, file_item in enumerate(files):
                    if not isinstance(file_item, dict) or not file_item.get("path"):
                        errors.append(f"{prefix}: setup-artifact.files[{index}] requires path.")
                        continue
                    # Exactly one payload source; mirrors the schema oneOf and the
                    # create-setup-files.py runtime guard.
                    modes = [
                        key
                        for key in ("content", "source-path", "content-base64")
                        if key in file_item
                    ]
                    if len(modes) != 1:
                        errors.append(
                            f"{prefix}: setup-artifact.files[{index}] must set exactly one of "
                            "content, source-path, content-base64."
                        )
                    source_path = file_item.get("source-path")
                    if (
                        isinstance(source_path, str)
                        and source_path
                        and (Path(source_path).is_absolute() or ".." in Path(source_path).parts)
                    ):
                        errors.append(
                            f"{prefix}: setup-artifact.files[{index}] source-path must be a "
                            "workspace-relative path without '..'."
                        )
        if scenario.mutation:
            if "hosted" not in scenario.runs:
                errors.append(f"{prefix}: mutation is supported for hosted scenarios.")
            # Mutation scenarios push/delete real branches on a remote, which act
            # (the local runner) cannot do; they are hosted-only.
            if "local" in scenario.runs:
                errors.append(f"{prefix}: mutation scenarios cannot run locally (hosted only).")
            if scenario.mutation.get("type") != "ephemeral-branch":
                errors.append(f"{prefix}: mutation.type must be ephemeral-branch.")
            if not scenario.mutation.get("fixture-path"):
                errors.append(f"{prefix}: mutation.fixture-path is required.")
            branch_prefix = scenario.mutation.get("branch-prefix")
            if not branch_prefix:
                errors.append(f"{prefix}: mutation.branch-prefix is required.")
            else:
                clash = seen_branch_prefixes.get(str(branch_prefix))
                if clash is not None:
                    errors.append(
                        f"{prefix}: mutation branch-prefix {branch_prefix!r} is already used by "
                        f"{clash.workflow.id} scenario {clash.id!r}; branch prefixes must be "
                        "unique across mutation scenarios."
                    )
                else:
                    seen_branch_prefixes[str(branch_prefix)] = scenario
            initial_files = scenario.mutation.get("initial-files")
            if not isinstance(initial_files, list):
                errors.append(f"{prefix}: mutation.initial-files must be a list.")
            elif not initial_files:
                errors.append(f"{prefix}: mutation.initial-files must be nonempty.")
            missing_inputs = _missing_mutation_inputs(scenario.workflow)
            if missing_inputs:
                errors.append(
                    f"{prefix}: mutation scenarios require the target workflow to accept "
                    f"inputs {missing_inputs}; {scenario.workflow.id} does not expose them."
                )
            if not scenario.writeback_payload:
                errors.append(f"{prefix}: mutation scenarios require writeback-payload.")
        if scenario.writeback_payload:
            if not scenario.mutation:
                errors.append(f"{prefix}: writeback-payload requires mutation.")
            if not scenario.writeback_payload.get("artifact-name"):
                errors.append(f"{prefix}: writeback-payload.artifact-name is required.")
            if not isinstance(scenario.writeback_payload.get("files"), list):
                errors.append(f"{prefix}: writeback-payload.files must be a list.")
            if not isinstance(scenario.writeback_payload.get("paths"), list):
                errors.append(f"{prefix}: writeback-payload.paths must be a list.")
            if not isinstance(scenario.writeback_payload.get("delete-paths", []), list):
                errors.append(f"{prefix}: writeback-payload.delete-paths must be a list.")
        if scenario.mutation:
            for assertion in scenario.assertions:
                assertion_type = assertion.get("type")
                if assertion_type in {"branch-file-contains", "branch-file-missing"}:
                    if not assertion.get("path"):
                        errors.append(f"{prefix}: {assertion_type} assertions require path.")
                elif assertion_type == "latest-commit-message-equals":
                    if "value" not in assertion:
                        errors.append(
                            f"{prefix}: latest-commit-message-equals assertions require value."
                        )
                else:
                    errors.append(
                        f"{prefix}: mutation scenario assertion type "
                        f"{assertion_type!r} is unsupported."
                    )
    return errors


def write_generated_test_workflows(workflows: list[Workflow], *, check: bool = False) -> list[Path]:
    """Generate one hosted and one local scenario workflow per catalog workflow.

    Each owning workflow's scenarios are emitted into their own small files
    (``devflows-scenarios-<id>.yaml`` for hosted, ``devflows-scenarios-<id>.local.yaml``
    for local/act) so no single generated file approaches the size GitHub
    startup-rejects. A runner-specific file is written only when the workflow has at
    least one scenario for that runner, and every generated file is checked against
    the same byte cap the published workflows use. Stale scenario files -- including
    the retired monolithic ``devflows-scenarios.yaml`` / ``devflows-local-scenarios.yaml``
    -- are pruned so the tree holds only the current per-workflow set.
    """
    scenarios = load_scenarios(workflows)
    outputs: dict[Path, str] = {}
    for workflow in workflows:
        owned = [scenario for scenario in scenarios if scenario.workflow.id == workflow.id]
        for runner, path_for, label in (
            ("hosted", hosted_scenario_path, "DevFlows Hosted Scenarios"),
            ("local", local_scenario_path, "DevFlows Local Scenarios"),
        ):
            if not any(runner in scenario.runs for scenario in owned):
                continue
            path = path_for(workflow.id)
            rendered = render_test_workflow(owned, runner=runner, name=f"{label}: {workflow.name}")
            content = rendered.rstrip() + "\n"
            # Guard each per-workflow file so a future workflow with huge scenarios
            # fails generation locally, not at startup on a hosted run.
            assert_within_size_cap(path.name, content)
            outputs[path] = content
    changed: list[Path] = []
    for path, content in outputs.items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    for orphan in _scenario_orphans(set(outputs)):
        changed.append(orphan)
        if not check:
            orphan.unlink()
    return changed


def _scenario_orphans(expected: set[Path]) -> list[Path]:
    """Generator-owned scenario files on disk this generation did not (re)produce."""
    found: dict[Path, None] = {}
    for pattern in _SCENARIO_FILE_GLOBS:
        for path in SCENARIOS_DIR.glob(pattern):
            found[path] = None
    return [path for path in sorted(found) if path not in expected]


def _requires_write(scenario: Scenario) -> bool:
    """Whether calling this scenario's workflow requires a write permission."""
    return any(level == "write" for level in _required_call_permissions(scenario.workflow).values())


def _guard_if(job: dict[str, Any], guard: str | None) -> None:
    """AND-combine a fork-safe guard into a job that has no existing ``if``."""
    if guard is None:
        return
    existing = job.get("if")
    job["if"] = f"({existing}) && ({guard})" if existing else guard


def _guard_always_if(job: dict[str, Any], guard: str | None) -> None:
    """Combine the guard with an assert/cleanup job's ``always()`` condition."""
    base = job.get("if") or "always()"
    job["if"] = f"{base} && ({guard})" if guard else base


def render_test_workflow(scenarios: list[Scenario], *, runner: str, name: str) -> str:
    selected = [scenario for scenario in scenarios if runner in scenario.runs]
    workflow: dict[str, Any] = {
        "name": name,
        "on": _on_block(runner),
        "permissions": {"contents": "read"},
        "jobs": {},
    }
    if runner == "hosted":
        workflow["permissions"]["actions"] = "read"
    jobs = workflow["jobs"]
    for scenario in selected:
        if scenario.is_validation_failure:
            # A plain checkout + run-the-validate-script job; no reusable call, no
            # write permission, so it needs no fork guard and runs under act too.
            jobs[f"{scenario.job_prefix}_validate"] = _validation_failure_job(
                scenario, runner=runner
            )
            continue
        # On hosted runners a write-requiring call cannot start on a fork PR, so
        # gate the whole scenario chain; read-only scenarios stay ungated and run
        # on every pull request. (Local runs never see fork PRs.)
        guard = _FORK_SAFE_IF if runner == "hosted" and _requires_write(scenario) else None
        if runner == "hosted" and scenario.mutation:
            setup_job_id = f"{scenario.job_prefix}_setup"
            call_job_id = f"{scenario.job_prefix}_call"
            assert_job_id = f"{scenario.job_prefix}_assert"
            setup_job = _ephemeral_branch_setup_job(scenario)
            call_job = _call_job(scenario, runner=runner)
            call_job["needs"] = setup_job_id
            assert_job = _assert_job(scenario, runner=runner)
            cleanup_job = _ephemeral_branch_cleanup_job(scenario)
            _guard_if(setup_job, guard)
            _guard_if(call_job, guard)
            _guard_always_if(assert_job, guard)
            _guard_always_if(cleanup_job, guard)
            jobs[setup_job_id] = setup_job
            jobs[call_job_id] = call_job
            jobs[assert_job_id] = assert_job
            jobs[f"{scenario.job_prefix}_cleanup"] = cleanup_job
            continue
        if runner == "local" and scenario.cleanup:
            jobs[f"{scenario.job_prefix}_clean"] = _cleanup_job(scenario)
        if runner == "hosted" and scenario.setup_artifact:
            setup_job = _setup_artifact_job(scenario)
            _guard_if(setup_job, guard)
            jobs[f"{scenario.job_prefix}_setup"] = setup_job
        call_job_id = f"{scenario.job_prefix}_call"
        call_job = _call_job(scenario, runner=runner)
        _guard_if(call_job, guard)
        needs = []
        if runner == "local" and scenario.cleanup:
            needs.append(f"{scenario.job_prefix}_clean")
        if runner == "hosted" and scenario.setup_artifact:
            needs.append(f"{scenario.job_prefix}_setup")
        if needs:
            call_job["needs"] = needs[0] if len(needs) == 1 else needs
        jobs[call_job_id] = call_job
        assert_job = _assert_job(scenario, runner=runner)
        _guard_always_if(assert_job, guard)
        jobs[f"{scenario.job_prefix}_assert"] = assert_job
    if not selected:
        jobs["no_scenarios"] = {
            "name": "No scenarios",
            "runs-on": "ubuntu-latest",
            "steps": [
                {"name": "No scenarios registered", "run": "echo 'No scenarios registered.'"}
            ],
        }
    if runner == "local":
        _require_act_guard(workflow)
        return _LOCAL_HEADER + dump_yaml(workflow)
    return _HOSTED_HEADER + dump_yaml(workflow)


def _require_act_guard(workflow: dict[str, Any]) -> None:
    """Prepend an act-only guard job that every other job depends on.

    The local scenario workflow is dispatchable on GitHub but only works under
    ``act`` (it targets the act ubuntu image and expects act's bind mounts).
    A guard job that fails unless ``$ACT`` is set makes an accidental GitHub
    dispatch fail fast with a clear message, and gating every job on it means
    nothing else wastes a runner.
    """
    guard_id = "require_act"
    guard_job = {
        "name": "Require act",
        "runs-on": "ubuntu-latest",
        "steps": [
            {
                "name": "Fail unless running under act",
                "shell": "bash",
                "run": (
                    'if [ "${ACT:-}" != "true" ]; then\n'
                    '  echo "::error::This local scenario workflow runs only under act. '
                    "Run 'task scenarios-local' locally; do not dispatch it on GitHub.\"\n"
                    "  exit 1\n"
                    "fi\n"
                    'echo "Running under act."'
                ),
            }
        ],
    }
    for job in workflow["jobs"].values():
        existing = job.get("needs")
        if existing is None:
            job["needs"] = guard_id
        elif isinstance(existing, str):
            job["needs"] = [guard_id, existing]
        else:
            job["needs"] = [guard_id, *existing]
    workflow["jobs"] = {guard_id: guard_job, **workflow["jobs"]}


def run_local_scenarios(workflows: list[Workflow]) -> int:
    write_generated_test_workflows(workflows)
    _cleanup_local_outputs(load_scenarios(workflows))
    # The scenarios are split into one local file per owning workflow. act's
    # --workflows takes a single path (and pointing it at the whole directory
    # would also pick up the hosted files, which share the workflow_dispatch
    # trigger), so run each per-workflow local file in turn.
    local_paths = [
        local_scenario_path(workflow.id)
        for workflow in workflows
        if local_scenario_path(workflow.id).exists()
    ]
    if not local_paths:
        print("No local scenarios to run.")
        return 0
    returncode = 0
    for path in local_paths:
        command = [
            "act",
            "workflow_dispatch",
            "--workflows",
            str(path),
            "--eventpath",
            str(LOCAL_EVENT_PATH),
            "--bind",
            "-P",
            ACT_PLATFORM,
        ]
        # Run every file even if an earlier one failed so one failing workflow does
        # not mask failures in the others; surface nonzero if any run fails.
        returncode = subprocess.run(command, check=False).returncode or returncode
    return returncode


def _on_block(runner: str) -> dict[str, Any]:
    if runner == "hosted":
        return {
            "pull_request": None,
            "push": {"branches": ["main"]},
            "workflow_dispatch": None,
        }
    return {"workflow_dispatch": None}


def _hosted_checkout_step(
    *, name: str = "Checkout repository", ref: str | None = None
) -> dict[str, Any]:
    """A pinned, credential-free checkout so hosted jobs can run harness scripts.

    Hosted assert/setup jobs run on fresh runners with no repository content, so
    they must check the repo out before invoking any ``harness/scenarios`` script.
    Read-only jobs use ``persist-credentials: false`` (they never push).
    """
    with_block: dict[str, Any] = {"persist-credentials": False}
    if ref is not None:
        with_block["ref"] = ref
    return {"name": name, "uses": CHECKOUT_REF, "with": with_block}


def _cleanup_job(scenario: Scenario) -> dict[str, Any]:
    script = "rm -rf " + " ".join(shlex.quote(path) for path in scenario.cleanup)
    return {
        "name": f"{scenario.workflow.name}: {scenario.name} cleanup",
        "runs-on": "ubuntu-latest",
        "steps": [{"name": "Remove previous scenario outputs", "run": script}],
    }


def _setup_artifact_job(scenario: Scenario) -> dict[str, Any]:
    return {
        "name": f"{scenario.workflow.name}: {scenario.name} setup",
        "runs-on": "ubuntu-latest",
        "steps": [
            _hosted_checkout_step(),
            {
                "name": "Create setup files",
                "shell": "bash",
                "env": {
                    "DEVFLOWS_SETUP_FILES": json.dumps(
                        scenario.setup_artifact.get("files", []), indent=2
                    )
                },
                "run": f"python {_script('create-setup-files.py')}",
            },
            {
                "name": "Upload setup artifact",
                "uses": UPLOAD_ARTIFACT_REF,
                "with": {
                    "name": scenario.setup_artifact["name"],
                    "path": scenario.setup_artifact["path"],
                    "if-no-files-found": "error",
                    "retention-days": 1,
                    "overwrite": True,
                },
            },
        ],
    }


def _ephemeral_branch_setup_job(scenario: Scenario) -> dict[str, Any]:
    return {
        "name": f"{scenario.workflow.name}: {scenario.name} setup",
        "runs-on": "ubuntu-latest",
        "permissions": {"contents": "write"},
        "outputs": {
            "artifact-name": "${{ steps.setup.outputs.artifact-name }}",
            "base-sha": "${{ steps.setup.outputs.base-sha }}",
            "branch": "${{ steps.setup.outputs.branch }}",
        },
        "steps": [
            {
                "name": "Checkout target repository",
                "uses": CHECKOUT_REF,
                "with": {"persist-credentials": True},
            },
            {
                "name": "Prepare branch and writeback payload",
                "id": "setup",
                "shell": "bash",
                "env": {
                    "DEVFLOWS_ARTIFACT_NAME": scenario.writeback_payload["artifact-name"],
                    "DEVFLOWS_BRANCH_PREFIX": scenario.mutation["branch-prefix"],
                    "DEVFLOWS_DELETE_PATHS": json.dumps(
                        scenario.writeback_payload.get("delete-paths", []), indent=2
                    ),
                    "DEVFLOWS_FIXTURE_PATH": scenario.mutation["fixture-path"],
                    "DEVFLOWS_INITIAL_FILES": json.dumps(
                        scenario.mutation.get("initial-files", []), indent=2
                    ),
                    "DEVFLOWS_PAYLOAD_FILES": json.dumps(
                        scenario.writeback_payload.get("files", []), indent=2
                    ),
                    "DEVFLOWS_PAYLOAD_PATHS": json.dumps(
                        scenario.writeback_payload.get("paths", []), indent=2
                    ),
                },
                "run": f"python {_script('setup-ephemeral-writeback.py')}",
            },
            {
                # include-hidden-files is REQUIRED, not cosmetic. create-payload.py
                # copies every selected file under .devflows-writeback/payload/files/
                # preserving its repo-relative path, so the payload legitimately holds
                # dotfiles and dot-directories (e.g. this fixture writes under
                # .devflows-e2e/, and real callers write back .github/**). Since
                # upload-artifact v4+, hidden paths are EXCLUDED by default, which
                # would silently drop those files from the artifact while keeping the
                # manifest that references them -- apply-payload.py then fails with
                # "Payload file is missing or invalid". Any uploader of a writeback
                # payload must opt in (publish.py's internal channel does the same).
                "name": "Upload writeback payload",
                "uses": UPLOAD_ARTIFACT_REF,
                "with": {
                    "name": "${{ steps.setup.outputs.artifact-name }}",
                    "path": ".devflows-writeback/payload",
                    "if-no-files-found": "error",
                    "retention-days": 1,
                    "overwrite": True,
                    "include-hidden-files": True,
                },
            },
        ],
    }


def _call_job(scenario: Scenario, *, runner: str) -> dict[str, Any]:
    job: dict[str, Any] = {
        "name": f"{scenario.workflow.name}: {scenario.name}",
        "uses": f"./.github/workflows/{scenario.workflow.id}.yaml",
        "with": scenario.inputs,
    }
    # Grant the permissions the called workflow's job tree declares. A read-only
    # caller of a writeback-capable workflow (e.g. pandoc, whose published form
    # embeds a `commit` job requesting contents: write) startup-fails otherwise —
    # GitHub rejects the run before any assertion executes. Consumers that call
    # these workflows must grant the same permissions on their calling job.
    permissions = _required_call_permissions(scenario.workflow)
    if permissions:
        job["permissions"] = permissions
    if runner == "hosted" and scenario.mutation:
        setup_job_id = f"{scenario.job_prefix}_setup"
        job["with"] = {
            **scenario.inputs,
            "commit-branch": f"${{{{ needs.{setup_job_id}.outputs.branch }}}}",
            "commit-expected-base-sha": f"${{{{ needs.{setup_job_id}.outputs.base-sha }}}}",
            "commit-repository": "${{ github.repository }}",
            "writeback-artifact-name": f"${{{{ needs.{setup_job_id}.outputs.artifact-name }}}}",
        }
    return job


def _validation_failure_job(scenario: Scenario, *, runner: str) -> dict[str, Any]:
    """A plain job that runs the target validate script and asserts it rejects.

    No reusable-workflow call is made: the job runs
    ``workflows/<id>/scripts/validate-inputs.py`` with the env the workflow's
    validate step would set, reconstructed from the scenario inputs and the
    workflow input defaults. The job stays green when the script rejects the
    inputs (nonzero exit) and fails if it unexpectedly accepts them, or if the
    required failure message is absent.

    Hosted runs check the repository out first (a fresh runner has no content);
    local (act) runs rely on the bind-mounted workspace, so a checkout is omitted
    there exactly as the local assert job does.
    """
    script_path = (scenario.workflow.support_path / VALIDATE_SCRIPT_NAME).as_posix()
    env: dict[str, str] = {
        "DEVFLOWS_VALIDATE_SCRIPT": script_path,
        **_validation_failure_env(scenario),
    }
    if scenario.failure_message_contains:
        env["DEVFLOWS_FAILURE_MESSAGE_CONTAINS"] = scenario.failure_message_contains
    steps: list[dict[str, Any]] = []
    if runner == "hosted":
        steps.append(_hosted_checkout_step())
    steps.append(
        {
            "name": "Assert validation rejects the inputs",
            "shell": "bash",
            "env": env,
            "run": f"python {_script('assert-validation-failure.py')}",
        }
    )
    return {
        "name": f"{scenario.workflow.name}: {scenario.name}",
        "runs-on": "ubuntu-latest",
        "steps": steps,
    }


def _assert_result_step(scenario: Scenario, call_job_id: str) -> dict[str, Any]:
    """Step asserting the call job reached the scenario's expected conclusion."""
    return {
        "name": "Assert scenario succeeded",
        "shell": "bash",
        "env": {"ACTUAL_RESULT": f"${{{{ needs.{call_job_id}.result }}}}"},
        "run": f"python {_script('assert-result.py')}",
    }


def _assert_job(scenario: Scenario, *, runner: str) -> dict[str, Any]:
    call_job_id = f"{scenario.job_prefix}_call"
    if runner == "hosted" and scenario.mutation:
        setup_job_id = f"{scenario.job_prefix}_setup"
        # Checkout must precede every script step: the ephemeral branch carries
        # both the harness scripts (inherited from the default branch) and the
        # writeback result under inspection.
        steps: list[dict[str, Any]] = [
            _hosted_checkout_step(
                name="Checkout ephemeral branch",
                ref=f"${{{{ needs.{setup_job_id}.outputs.branch }}}}",
            ),
            _assert_result_step(scenario, call_job_id),
            {
                "name": "Assert ephemeral branch",
                "shell": "bash",
                "env": {
                    "DEVFLOWS_ASSERTIONS": json.dumps(scenario.assertions, indent=2),
                    "DEVFLOWS_FIXTURE_PATH": scenario.mutation["fixture-path"],
                },
                "run": f"python {_script('assert-ephemeral-writeback.py')}",
            },
        ]
        return {
            "name": f"{scenario.workflow.name}: {scenario.name} assertions",
            "runs-on": "ubuntu-latest",
            "needs": [setup_job_id, call_job_id],
            "if": "always()",
            "steps": steps,
        }

    steps: list[dict[str, Any]] = []
    if runner == "hosted":
        # Fresh runner without repository content; check out before any script.
        steps.append(_hosted_checkout_step())
    steps.append(_assert_result_step(scenario, call_job_id))
    if runner == "hosted" and scenario.artifact:
        download_path = str(
            scenario.artifact.get("path") or f".devflows-test-artifacts/{scenario.id}"
        )
        steps.append(
            {
                "name": "Download scenario artifact",
                "uses": DOWNLOAD_ARTIFACT_REF,
                "with": {
                    "name": scenario.artifact["name"],
                    "path": download_path,
                },
            }
        )
    for assertion in scenario.assertions:
        steps.extend(_assertion_steps(scenario, assertion, runner=runner))
    return {
        "name": f"{scenario.workflow.name}: {scenario.name} assertions",
        "runs-on": "ubuntu-latest",
        "needs": call_job_id,
        "if": "always()",
        "steps": steps,
    }


def _ephemeral_branch_cleanup_job(scenario: Scenario) -> dict[str, Any]:
    setup_job_id = f"{scenario.job_prefix}_setup"
    call_job_id = f"{scenario.job_prefix}_call"
    assert_job_id = f"{scenario.job_prefix}_assert"
    return {
        "name": f"{scenario.workflow.name}: {scenario.name} cleanup",
        "runs-on": "ubuntu-latest",
        "needs": [setup_job_id, call_job_id, assert_job_id],
        "if": "always()",
        "permissions": {"contents": "write"},
        "steps": [
            {
                "name": "Checkout target repository",
                "uses": CHECKOUT_REF,
                "with": {"persist-credentials": True},
            },
            {
                "name": "Delete ephemeral branch",
                "shell": "bash",
                # Cleanup recomputes the deterministic branch name from the prefix
                # and run identifiers instead of reading the setup output, so a
                # setup that fails after pushing but before emitting outputs cannot
                # orphan the branch.
                "env": {"DEVFLOWS_BRANCH_PREFIX": scenario.mutation["branch-prefix"]},
                "run": f"python {_script('cleanup-ephemeral-branch.py')}",
            },
        ],
    }


def _assertion_steps(
    scenario: Scenario, assertion: dict[str, Any], *, runner: str
) -> list[dict[str, Any]]:
    assertion_type = assertion["type"]
    if assertion_type == "workflow-output-equals":
        output_name = str(assertion["name"])
        call_job_id = f"{scenario.job_prefix}_call"
        return [
            {
                "name": f"Assert output {output_name}",
                "shell": "bash",
                "env": {
                    "ASSERT_NAME": output_name,
                    "EXPECTED": str(assertion["value"]),
                    "ACTUAL": f"${{{{ needs.{call_job_id}.outputs.{output_name} }}}}",
                },
                "run": f"python {_script('assert-equals.py')}",
            }
        ]
    path = _assertion_path(scenario, assertion, runner=runner)
    if assertion_type in {"file-exists", "file-glob-exists"}:
        is_glob = assertion_type == "file-glob-exists"
        env = {"ASSERT_PATH": path}
        if is_glob:
            # assert-file-exists.py treats ASSERT_PATH as a glob requiring >=1
            # match when ASSERT_GLOB is set.
            env["ASSERT_GLOB"] = "1"
        label = "matches glob" if is_glob else "exists"
        return [
            {
                "name": f"Assert file {label}: {assertion['path']}",
                "shell": "bash",
                "env": env,
                "run": f"python {_script('assert-file-exists.py')}",
            }
        ]
    return [
        {
            "name": f"Assert file contains: {assertion['path']}",
            "shell": "bash",
            "env": {"ASSERT_PATH": path, "ASSERT_TEXT": str(assertion["text"])},
            "run": f"python {_script('assert-file-contains.py')}",
        }
    ]


def _assertion_path(scenario: Scenario, assertion: dict[str, Any], *, runner: str) -> str:
    path = str(assertion["path"])
    if runner == "hosted" and scenario.artifact:
        download_path = str(
            scenario.artifact.get("path") or f".devflows-test-artifacts/{scenario.id}"
        )
        return str(Path(download_path) / path)
    return path


def _cleanup_local_outputs(scenarios: list[Scenario]) -> None:
    for scenario in scenarios:
        if "local" not in scenario.runs:
            continue
        for path in scenario.cleanup:
            target = Path(path)
            if target.is_dir():
                shutil.rmtree(target)
            elif target.exists():
                target.unlink()


def _has_file_assertions(scenario: Scenario) -> bool:
    return any(
        assertion.get("type") in {"file-exists", "file-glob-exists", "file-contains"}
        for assertion in scenario.assertions
    )
